use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use ironworks::excel::Row;
use ironworks::sestring::SeString;
use std::result::Result;
impl MetadataAdapter for ContentFinderCondition {
    fn name() -> String {
        "ContentFinderCondition".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(ContentFinderCondition::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct ContentFinderCondition {
    pub r#short_code: SeString,
    pub r#territory_type: u16,
    pub r#content_link_type: u8,
    pub r#content: u16,
    pub r#pv_p: bool,
    pub r#unknown5: bool,
    pub r#unknown6: u8,
    pub r#unknown7: u32,
    pub r#unknown8: u32,
    pub r#accept_class_job_category: u8,
    pub r#content_member_type: u8,
    pub r#unknown11: u8,
    pub r#unknown12: u8,
    pub r#unknown13: u8,
    pub r#unlock_quest: u32,
    pub r#unknown15: u8,
    pub r#unknown16: u32,
    pub r#class_job_level_required: u8,
    pub r#class_job_level_sync: u8,
    pub r#item_level_required: u16,
    pub r#item_level_sync: u16,
    pub r#unknown21: bool,
    pub r#allow_undersized: bool,
    pub r#unknown23: bool,
    pub r#unknown24: bool,
    pub r#allow_replacement: bool,
    pub r#unknown26: bool,
    pub r#allow_explorer_mode: bool,
    pub r#unknown28: bool,
    pub r#unknown29: bool,
    pub r#unknown30: u8,
    pub r#unknown31: bool,
    pub r#high_end_duty: bool,
    pub r#unknown33: bool,
    pub r#unknown34: bool,
    pub r#unknown35: u8,
    pub r#unknown36: bool,
    pub r#unknown37: bool,
    pub r#duty_recorder_allowed: bool,
    pub r#unknown39: bool,
    pub r#unknown40: bool,
    pub r#unknown41: bool,
    pub r#unknown42: bool,
    pub r#name: SeString,
    pub r#name_short: SeString,
    pub r#content_type: u8,
    pub r#transient_key: u8,
    pub r#unknown47: u32,
    pub r#transient: u32,
    pub r#sort_key: u16,
    pub r#image: u32,
    pub r#icon: u32,
    pub r#unknown52: i8,
    pub r#unknown53: i32,
    pub r#unknown54: bool,
    pub r#unknown55: bool,
    pub r#unknown56: i32,
    pub r#leveling_roulette: u8,
    pub r#high_level_roulette: bool,
    pub r#msq_roulette: bool,
    pub r#guild_hest_roulette: bool,
    pub r#expert_roulette: bool,
    pub r#trial_roulette: bool,
    pub r#daily_frontline_challenge: bool,
    pub r#level_cap_roulette: bool,
    pub r#mentor_roulette: bool,
    pub r#unknown66: bool,
    pub r#unknown67: bool,
    pub r#unknown68: bool,
    pub r#unknown69: bool,
    pub r#unknown70: bool,
    pub r#alliance_roulette: bool,
    pub r#feast_team_roulette: bool,
    pub r#normal_raid_roulette: bool,
    pub r#unknown74: bool,
    pub r#unknown75: bool,
    pub r#unknown76: bool,
    pub r#unknown77: bool,
    pub r#unknown78: bool,
    pub r#unknown79: bool,
    pub r#unknown80: bool,
    pub r#unknown81: bool,
    pub r#unknown82: bool,
    pub r#unknown83: bool,
    pub r#unknown84: bool,
    pub r#unknown85: bool,
    pub r#unknown86: bool,
    pub r#unknown87: bool,
    pub r#unknown88: bool,
    pub r#unknown89: bool,
    pub r#unknown90: bool,
    pub r#unknown91: bool,
    pub r#unknown92: bool,
    pub r#unknown93: bool,
    pub r#unknown94: bool,
    pub r#unknown95: bool,
    pub r#unknown96: bool,
    pub r#unknown97: bool,
    pub r#unknown98: bool,
}
impl ContentFinderCondition {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#short_code: row.field(0usize + offset)?.into_string()?,
            r#territory_type: row.field(1usize + offset)?.into_u16()?,
            r#content_link_type: row.field(2usize + offset)?.into_u8()?,
            r#content: row.field(3usize + offset)?.into_u16()?,
            r#pv_p: row.field(4usize + offset)?.into_bool()?,
            r#unknown5: row.field(5usize + offset)?.into_bool()?,
            r#unknown6: row.field(6usize + offset)?.into_u8()?,
            r#unknown7: row.field(7usize + offset)?.into_u32()?,
            r#unknown8: row.field(8usize + offset)?.into_u32()?,
            r#accept_class_job_category: row.field(9usize + offset)?.into_u8()?,
            r#content_member_type: row.field(10usize + offset)?.into_u8()?,
            r#unknown11: row.field(11usize + offset)?.into_u8()?,
            r#unknown12: row.field(12usize + offset)?.into_u8()?,
            r#unknown13: row.field(13usize + offset)?.into_u8()?,
            r#unlock_quest: row.field(14usize + offset)?.into_u32()?,
            r#unknown15: row.field(15usize + offset)?.into_u8()?,
            r#unknown16: row.field(16usize + offset)?.into_u32()?,
            r#class_job_level_required: row.field(17usize + offset)?.into_u8()?,
            r#class_job_level_sync: row.field(18usize + offset)?.into_u8()?,
            r#item_level_required: row.field(19usize + offset)?.into_u16()?,
            r#item_level_sync: row.field(20usize + offset)?.into_u16()?,
            r#unknown21: row.field(21usize + offset)?.into_bool()?,
            r#allow_undersized: row.field(22usize + offset)?.into_bool()?,
            r#unknown23: row.field(23usize + offset)?.into_bool()?,
            r#unknown24: row.field(24usize + offset)?.into_bool()?,
            r#allow_replacement: row.field(25usize + offset)?.into_bool()?,
            r#unknown26: row.field(26usize + offset)?.into_bool()?,
            r#allow_explorer_mode: row.field(27usize + offset)?.into_bool()?,
            r#unknown28: row.field(28usize + offset)?.into_bool()?,
            r#unknown29: row.field(29usize + offset)?.into_bool()?,
            r#unknown30: row.field(30usize + offset)?.into_u8()?,
            r#unknown31: row.field(31usize + offset)?.into_bool()?,
            r#high_end_duty: row.field(32usize + offset)?.into_bool()?,
            r#unknown33: row.field(33usize + offset)?.into_bool()?,
            r#unknown34: row.field(34usize + offset)?.into_bool()?,
            r#unknown35: row.field(35usize + offset)?.into_u8()?,
            r#unknown36: row.field(36usize + offset)?.into_bool()?,
            r#unknown37: row.field(37usize + offset)?.into_bool()?,
            r#duty_recorder_allowed: row.field(38usize + offset)?.into_bool()?,
            r#unknown39: row.field(39usize + offset)?.into_bool()?,
            r#unknown40: row.field(40usize + offset)?.into_bool()?,
            r#unknown41: row.field(41usize + offset)?.into_bool()?,
            r#unknown42: row.field(42usize + offset)?.into_bool()?,
            r#name: row.field(43usize + offset)?.into_string()?,
            r#name_short: row.field(44usize + offset)?.into_string()?,
            r#content_type: row.field(45usize + offset)?.into_u8()?,
            r#transient_key: row.field(46usize + offset)?.into_u8()?,
            r#unknown47: row.field(47usize + offset)?.into_u32()?,
            r#transient: row.field(48usize + offset)?.into_u32()?,
            r#sort_key: row.field(49usize + offset)?.into_u16()?,
            r#image: row.field(50usize + offset)?.into_u32()?,
            r#icon: row.field(51usize + offset)?.into_u32()?,
            r#unknown52: row.field(52usize + offset)?.into_i8()?,
            r#unknown53: row.field(53usize + offset)?.into_i32()?,
            r#unknown54: row.field(54usize + offset)?.into_bool()?,
            r#unknown55: row.field(55usize + offset)?.into_bool()?,
            r#unknown56: row.field(56usize + offset)?.into_i32()?,
            r#leveling_roulette: row.field(57usize + offset)?.into_u8()?,
            r#high_level_roulette: row.field(58usize + offset)?.into_bool()?,
            r#msq_roulette: row.field(59usize + offset)?.into_bool()?,
            r#guild_hest_roulette: row.field(60usize + offset)?.into_bool()?,
            r#expert_roulette: row.field(61usize + offset)?.into_bool()?,
            r#trial_roulette: row.field(62usize + offset)?.into_bool()?,
            r#daily_frontline_challenge: row.field(63usize + offset)?.into_bool()?,
            r#level_cap_roulette: row.field(64usize + offset)?.into_bool()?,
            r#mentor_roulette: row.field(65usize + offset)?.into_bool()?,
            r#unknown66: row.field(66usize + offset)?.into_bool()?,
            r#unknown67: row.field(67usize + offset)?.into_bool()?,
            r#unknown68: row.field(68usize + offset)?.into_bool()?,
            r#unknown69: row.field(69usize + offset)?.into_bool()?,
            r#unknown70: row.field(70usize + offset)?.into_bool()?,
            r#alliance_roulette: row.field(71usize + offset)?.into_bool()?,
            r#feast_team_roulette: row.field(72usize + offset)?.into_bool()?,
            r#normal_raid_roulette: row.field(73usize + offset)?.into_bool()?,
            r#unknown74: row.field(74usize + offset)?.into_bool()?,
            r#unknown75: row.field(75usize + offset)?.into_bool()?,
            r#unknown76: row.field(76usize + offset)?.into_bool()?,
            r#unknown77: row.field(77usize + offset)?.into_bool()?,
            r#unknown78: row.field(78usize + offset)?.into_bool()?,
            r#unknown79: row.field(79usize + offset)?.into_bool()?,
            r#unknown80: row.field(80usize + offset)?.into_bool()?,
            r#unknown81: row.field(81usize + offset)?.into_bool()?,
            r#unknown82: row.field(82usize + offset)?.into_bool()?,
            r#unknown83: row.field(83usize + offset)?.into_bool()?,
            r#unknown84: row.field(84usize + offset)?.into_bool()?,
            r#unknown85: row.field(85usize + offset)?.into_bool()?,
            r#unknown86: row.field(86usize + offset)?.into_bool()?,
            r#unknown87: row.field(87usize + offset)?.into_bool()?,
            r#unknown88: row.field(88usize + offset)?.into_bool()?,
            r#unknown89: row.field(89usize + offset)?.into_bool()?,
            r#unknown90: row.field(90usize + offset)?.into_bool()?,
            r#unknown91: row.field(91usize + offset)?.into_bool()?,
            r#unknown92: row.field(92usize + offset)?.into_bool()?,
            r#unknown93: row.field(93usize + offset)?.into_bool()?,
            r#unknown94: row.field(94usize + offset)?.into_bool()?,
            r#unknown95: row.field(95usize + offset)?.into_bool()?,
            r#unknown96: row.field(96usize + offset)?.into_bool()?,
            r#unknown97: row.field(97usize + offset)?.into_bool()?,
            r#unknown98: row.field(98usize + offset)?.into_bool()?,
        })
    }
}
