use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use crate::utility::read_array;
use ironworks::excel::Row;
use ironworks::sestring::SeString;
use std::result::Result;
use std::vec::Vec;
impl MetadataAdapter for Fate {
    fn name() -> String {
        "Fate".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(Fate::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct Fate {
    pub r#name: SeString,
    pub r#description: SeString,
    pub r#objective: SeString,
    pub r#status_text: Vec<SeString>,
    pub r#eureka_fate: u8,
    pub r#rule: u8,
    pub r#fate_rule_ex: u16,
    pub r#location: u32,
    pub r#class_job_level: u8,
    pub r#class_job_level_max: u8,
    pub r#event_item: u32,
    pub r#type_to_do_value: Vec<u8>,
    pub r#icon_objective: u32,
    pub r#icon_map: u32,
    pub r#icon_inactive_map: u32,
    pub r#music: u16,
    pub r#lgb_guard_npc_location: u32,
    pub r#screen_image_accept: u16,
    pub r#screen_image_complete: u16,
    pub r#screen_image_failed: u16,
    pub r#unknown24: u8,
    pub r#required_quest: u32,
    pub r#special_fate: bool,
    pub r#unknown27: bool,
    pub r#given_status: u16,
    pub r#unknown29: u16,
    pub r#advent_event: bool,
    pub r#moon_faire_event: bool,
    pub r#unknown32: bool,
    pub r#fate_chain: u32,
    pub r#unknown34: u8,
    pub r#unknown35: u32,
    pub r#array_index: u16,
    pub r#unknown37: u32,
    pub r#req_event_item: u32,
    pub r#turn_in_event_item: u32,
    pub r#unknown40: u32,
    pub r#unknown41: u32,
    pub r#unknown42: u32,
    pub r#objective_icon: Vec<u32>,
    pub r#unknown51: u32,
    pub r#unknown52: u32,
    pub r#unknown53: u32,
    pub r#unknown54: u32,
    pub r#unknown55: u32,
    pub r#unknown56: u32,
    pub r#unknown57: u32,
    pub r#unknown58: u32,
    pub r#unknown59: u32,
    pub r#unknown60: u32,
    pub r#unknown61: u32,
    pub r#unknown62: u32,
    pub r#unknown63: u32,
    pub r#unknown64: u32,
    pub r#unknown65: u32,
    pub r#unknown66: u32,
    pub r#unknown67: u32,
    pub r#unknown68: u32,
    pub r#unknown69: u32,
    pub r#unknown70: u32,
    pub r#unknown71: u32,
    pub r#unknown72: u32,
    pub r#unknown73: u32,
    pub r#unknown74: u32,
    pub r#unknown75: u32,
    pub r#unknown76: u32,
    pub r#unknown77: u32,
    pub r#unknown78: u32,
    pub r#unknown79: u16,
    pub r#unknown80: u16,
    pub r#unknown81: u16,
    pub r#unknown82: u16,
    pub r#unknown83: u16,
    pub r#unknown84: u16,
    pub r#unknown85: u16,
    pub r#unknown86: u16,
    pub r#unknown87: u16,
    pub r#unknown88: u16,
    pub r#unknown89: u16,
    pub r#unknown90: u16,
    pub r#unknown91: u16,
    pub r#unknown92: u16,
    pub r#unknown93: u16,
    pub r#unknown94: u16,
    pub r#unknown95: u16,
    pub r#unknown96: u16,
    pub r#unknown97: u16,
    pub r#unknown98: u16,
    pub r#unknown99: u16,
    pub r#unknown100: u16,
    pub r#unknown101: u16,
    pub r#unknown102: u16,
    pub r#unknown103: u16,
    pub r#unknown104: u16,
    pub r#unknown105: u16,
    pub r#unknown106: u16,
    pub r#unknown107: u16,
    pub r#unknown108: u16,
    pub r#unknown109: u16,
    pub r#unknown110: u16,
}
impl Fate {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#name: row.field(0usize + offset)?.into_string()?,
            r#description: row.field(1usize + offset)?.into_string()?,
            r#objective: row.field(2usize + offset)?.into_string()?,
            r#status_text: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(3usize + offset)?.into_string()?) },
            )?,
            r#eureka_fate: row.field(6usize + offset)?.into_u8()?,
            r#rule: row.field(7usize + offset)?.into_u8()?,
            r#fate_rule_ex: row.field(8usize + offset)?.into_u16()?,
            r#location: row.field(9usize + offset)?.into_u32()?,
            r#class_job_level: row.field(10usize + offset)?.into_u8()?,
            r#class_job_level_max: row.field(11usize + offset)?.into_u8()?,
            r#event_item: row.field(12usize + offset)?.into_u32()?,
            r#type_to_do_value: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(13usize + offset)?.into_u8()?) },
            )?,
            r#icon_objective: row.field(16usize + offset)?.into_u32()?,
            r#icon_map: row.field(17usize + offset)?.into_u32()?,
            r#icon_inactive_map: row.field(18usize + offset)?.into_u32()?,
            r#music: row.field(19usize + offset)?.into_u16()?,
            r#lgb_guard_npc_location: row.field(20usize + offset)?.into_u32()?,
            r#screen_image_accept: row.field(21usize + offset)?.into_u16()?,
            r#screen_image_complete: row.field(22usize + offset)?.into_u16()?,
            r#screen_image_failed: row.field(23usize + offset)?.into_u16()?,
            r#unknown24: row.field(24usize + offset)?.into_u8()?,
            r#required_quest: row.field(25usize + offset)?.into_u32()?,
            r#special_fate: row.field(26usize + offset)?.into_bool()?,
            r#unknown27: row.field(27usize + offset)?.into_bool()?,
            r#given_status: row.field(28usize + offset)?.into_u16()?,
            r#unknown29: row.field(29usize + offset)?.into_u16()?,
            r#advent_event: row.field(30usize + offset)?.into_bool()?,
            r#moon_faire_event: row.field(31usize + offset)?.into_bool()?,
            r#unknown32: row.field(32usize + offset)?.into_bool()?,
            r#fate_chain: row.field(33usize + offset)?.into_u32()?,
            r#unknown34: row.field(34usize + offset)?.into_u8()?,
            r#unknown35: row.field(35usize + offset)?.into_u32()?,
            r#array_index: row.field(36usize + offset)?.into_u16()?,
            r#unknown37: row.field(37usize + offset)?.into_u32()?,
            r#req_event_item: row.field(38usize + offset)?.into_u32()?,
            r#turn_in_event_item: row.field(39usize + offset)?.into_u32()?,
            r#unknown40: row.field(40usize + offset)?.into_u32()?,
            r#unknown41: row.field(41usize + offset)?.into_u32()?,
            r#unknown42: row.field(42usize + offset)?.into_u32()?,
            r#objective_icon: read_array(
                offset,
                8usize,
                1usize,
                |offset| { Result::Ok(row.field(43usize + offset)?.into_u32()?) },
            )?,
            r#unknown51: row.field(51usize + offset)?.into_u32()?,
            r#unknown52: row.field(52usize + offset)?.into_u32()?,
            r#unknown53: row.field(53usize + offset)?.into_u32()?,
            r#unknown54: row.field(54usize + offset)?.into_u32()?,
            r#unknown55: row.field(55usize + offset)?.into_u32()?,
            r#unknown56: row.field(56usize + offset)?.into_u32()?,
            r#unknown57: row.field(57usize + offset)?.into_u32()?,
            r#unknown58: row.field(58usize + offset)?.into_u32()?,
            r#unknown59: row.field(59usize + offset)?.into_u32()?,
            r#unknown60: row.field(60usize + offset)?.into_u32()?,
            r#unknown61: row.field(61usize + offset)?.into_u32()?,
            r#unknown62: row.field(62usize + offset)?.into_u32()?,
            r#unknown63: row.field(63usize + offset)?.into_u32()?,
            r#unknown64: row.field(64usize + offset)?.into_u32()?,
            r#unknown65: row.field(65usize + offset)?.into_u32()?,
            r#unknown66: row.field(66usize + offset)?.into_u32()?,
            r#unknown67: row.field(67usize + offset)?.into_u32()?,
            r#unknown68: row.field(68usize + offset)?.into_u32()?,
            r#unknown69: row.field(69usize + offset)?.into_u32()?,
            r#unknown70: row.field(70usize + offset)?.into_u32()?,
            r#unknown71: row.field(71usize + offset)?.into_u32()?,
            r#unknown72: row.field(72usize + offset)?.into_u32()?,
            r#unknown73: row.field(73usize + offset)?.into_u32()?,
            r#unknown74: row.field(74usize + offset)?.into_u32()?,
            r#unknown75: row.field(75usize + offset)?.into_u32()?,
            r#unknown76: row.field(76usize + offset)?.into_u32()?,
            r#unknown77: row.field(77usize + offset)?.into_u32()?,
            r#unknown78: row.field(78usize + offset)?.into_u32()?,
            r#unknown79: row.field(79usize + offset)?.into_u16()?,
            r#unknown80: row.field(80usize + offset)?.into_u16()?,
            r#unknown81: row.field(81usize + offset)?.into_u16()?,
            r#unknown82: row.field(82usize + offset)?.into_u16()?,
            r#unknown83: row.field(83usize + offset)?.into_u16()?,
            r#unknown84: row.field(84usize + offset)?.into_u16()?,
            r#unknown85: row.field(85usize + offset)?.into_u16()?,
            r#unknown86: row.field(86usize + offset)?.into_u16()?,
            r#unknown87: row.field(87usize + offset)?.into_u16()?,
            r#unknown88: row.field(88usize + offset)?.into_u16()?,
            r#unknown89: row.field(89usize + offset)?.into_u16()?,
            r#unknown90: row.field(90usize + offset)?.into_u16()?,
            r#unknown91: row.field(91usize + offset)?.into_u16()?,
            r#unknown92: row.field(92usize + offset)?.into_u16()?,
            r#unknown93: row.field(93usize + offset)?.into_u16()?,
            r#unknown94: row.field(94usize + offset)?.into_u16()?,
            r#unknown95: row.field(95usize + offset)?.into_u16()?,
            r#unknown96: row.field(96usize + offset)?.into_u16()?,
            r#unknown97: row.field(97usize + offset)?.into_u16()?,
            r#unknown98: row.field(98usize + offset)?.into_u16()?,
            r#unknown99: row.field(99usize + offset)?.into_u16()?,
            r#unknown100: row.field(100usize + offset)?.into_u16()?,
            r#unknown101: row.field(101usize + offset)?.into_u16()?,
            r#unknown102: row.field(102usize + offset)?.into_u16()?,
            r#unknown103: row.field(103usize + offset)?.into_u16()?,
            r#unknown104: row.field(104usize + offset)?.into_u16()?,
            r#unknown105: row.field(105usize + offset)?.into_u16()?,
            r#unknown106: row.field(106usize + offset)?.into_u16()?,
            r#unknown107: row.field(107usize + offset)?.into_u16()?,
            r#unknown108: row.field(108usize + offset)?.into_u16()?,
            r#unknown109: row.field(109usize + offset)?.into_u16()?,
            r#unknown110: row.field(110usize + offset)?.into_u16()?,
        })
    }
}
