use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use crate::utility::read_array;
use ironworks::excel::Row;
use std::result::Result;
use std::vec::Vec;
impl MetadataAdapter for GFATE {
    fn name() -> String {
        "GFATE".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(GFATE::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct GFATE {
    pub r#unknown0: u8,
    pub r#unknown1: u8,
    pub r#unknown2: u32,
    pub r#unknown3: u16,
    pub r#unknown4: u16,
    pub r#unknown5: u16,
    pub r#unknown6: u32,
    pub r#lgb_pop_range: Vec<u32>,
    pub r#unknown22: u32,
    pub r#icon: Vec<u32>,
    pub r#unknown38: u32,
    pub r#unknown39: bool,
    pub r#unknown40: bool,
    pub r#unknown41: bool,
    pub r#unknown42: bool,
    pub r#unknown43: bool,
    pub r#unknown44: bool,
    pub r#unknown45: bool,
    pub r#unknown46: bool,
    pub r#unknown47: bool,
    pub r#unknown48: bool,
    pub r#unknown49: bool,
    pub r#unknown50: bool,
    pub r#unknown51: bool,
    pub r#unknown52: bool,
    pub r#unknown53: bool,
    pub r#unknown54: bool,
    pub r#unknown55: bool,
    pub r#unknown56: bool,
    pub r#unknown57: bool,
    pub r#unknown58: bool,
    pub r#unknown59: bool,
    pub r#unknown60: bool,
    pub r#unknown61: bool,
    pub r#unknown62: bool,
    pub r#unknown63: bool,
    pub r#unknown64: bool,
    pub r#unknown65: bool,
    pub r#unknown66: bool,
    pub r#unknown67: bool,
    pub r#unknown68: bool,
    pub r#unknown69: bool,
    pub r#unknown70: bool,
    pub r#unknown71: bool,
    pub r#unknown72: bool,
    pub r#unknown73: bool,
    pub r#unknown74: bool,
    pub r#unknown75: bool,
    pub r#unknown76: bool,
    pub r#unknown77: bool,
    pub r#unknown78: bool,
    pub r#unknown79: bool,
    pub r#unknown80: bool,
    pub r#unknown81: bool,
    pub r#unknown82: bool,
    pub r#unknown83: bool,
    pub r#unknown84: bool,
    pub r#unknown85: bool,
    pub r#unknown86: bool,
}
impl GFATE {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#unknown0: row.field(0usize + offset)?.into_u8()?,
            r#unknown1: row.field(1usize + offset)?.into_u8()?,
            r#unknown2: row.field(2usize + offset)?.into_u32()?,
            r#unknown3: row.field(3usize + offset)?.into_u16()?,
            r#unknown4: row.field(4usize + offset)?.into_u16()?,
            r#unknown5: row.field(5usize + offset)?.into_u16()?,
            r#unknown6: row.field(6usize + offset)?.into_u32()?,
            r#lgb_pop_range: read_array(
                offset,
                15usize,
                1usize,
                |offset| { Result::Ok(row.field(7usize + offset)?.into_u32()?) },
            )?,
            r#unknown22: row.field(22usize + offset)?.into_u32()?,
            r#icon: read_array(
                offset,
                15usize,
                1usize,
                |offset| { Result::Ok(row.field(23usize + offset)?.into_u32()?) },
            )?,
            r#unknown38: row.field(38usize + offset)?.into_u32()?,
            r#unknown39: row.field(39usize + offset)?.into_bool()?,
            r#unknown40: row.field(40usize + offset)?.into_bool()?,
            r#unknown41: row.field(41usize + offset)?.into_bool()?,
            r#unknown42: row.field(42usize + offset)?.into_bool()?,
            r#unknown43: row.field(43usize + offset)?.into_bool()?,
            r#unknown44: row.field(44usize + offset)?.into_bool()?,
            r#unknown45: row.field(45usize + offset)?.into_bool()?,
            r#unknown46: row.field(46usize + offset)?.into_bool()?,
            r#unknown47: row.field(47usize + offset)?.into_bool()?,
            r#unknown48: row.field(48usize + offset)?.into_bool()?,
            r#unknown49: row.field(49usize + offset)?.into_bool()?,
            r#unknown50: row.field(50usize + offset)?.into_bool()?,
            r#unknown51: row.field(51usize + offset)?.into_bool()?,
            r#unknown52: row.field(52usize + offset)?.into_bool()?,
            r#unknown53: row.field(53usize + offset)?.into_bool()?,
            r#unknown54: row.field(54usize + offset)?.into_bool()?,
            r#unknown55: row.field(55usize + offset)?.into_bool()?,
            r#unknown56: row.field(56usize + offset)?.into_bool()?,
            r#unknown57: row.field(57usize + offset)?.into_bool()?,
            r#unknown58: row.field(58usize + offset)?.into_bool()?,
            r#unknown59: row.field(59usize + offset)?.into_bool()?,
            r#unknown60: row.field(60usize + offset)?.into_bool()?,
            r#unknown61: row.field(61usize + offset)?.into_bool()?,
            r#unknown62: row.field(62usize + offset)?.into_bool()?,
            r#unknown63: row.field(63usize + offset)?.into_bool()?,
            r#unknown64: row.field(64usize + offset)?.into_bool()?,
            r#unknown65: row.field(65usize + offset)?.into_bool()?,
            r#unknown66: row.field(66usize + offset)?.into_bool()?,
            r#unknown67: row.field(67usize + offset)?.into_bool()?,
            r#unknown68: row.field(68usize + offset)?.into_bool()?,
            r#unknown69: row.field(69usize + offset)?.into_bool()?,
            r#unknown70: row.field(70usize + offset)?.into_bool()?,
            r#unknown71: row.field(71usize + offset)?.into_bool()?,
            r#unknown72: row.field(72usize + offset)?.into_bool()?,
            r#unknown73: row.field(73usize + offset)?.into_bool()?,
            r#unknown74: row.field(74usize + offset)?.into_bool()?,
            r#unknown75: row.field(75usize + offset)?.into_bool()?,
            r#unknown76: row.field(76usize + offset)?.into_bool()?,
            r#unknown77: row.field(77usize + offset)?.into_bool()?,
            r#unknown78: row.field(78usize + offset)?.into_bool()?,
            r#unknown79: row.field(79usize + offset)?.into_bool()?,
            r#unknown80: row.field(80usize + offset)?.into_bool()?,
            r#unknown81: row.field(81usize + offset)?.into_bool()?,
            r#unknown82: row.field(82usize + offset)?.into_bool()?,
            r#unknown83: row.field(83usize + offset)?.into_bool()?,
            r#unknown84: row.field(84usize + offset)?.into_bool()?,
            r#unknown85: row.field(85usize + offset)?.into_bool()?,
            r#unknown86: row.field(86usize + offset)?.into_bool()?,
        })
    }
}
