use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use ironworks::excel::Row;
use ironworks::sestring::SeString;
use std::result::Result;
impl MetadataAdapter for Opening {
    fn name() -> String {
        "Opening".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(Opening::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct Opening {
    pub r#name: SeString,
    pub r#quest: u32,
    pub r#unknown2: SeString,
    pub r#unknown3: SeString,
    pub r#unknown4: SeString,
    pub r#unknown5: SeString,
    pub r#unknown6: SeString,
    pub r#unknown7: SeString,
    pub r#unknown8: SeString,
    pub r#unknown9: SeString,
    pub r#unknown10: SeString,
    pub r#unknown11: SeString,
    pub r#unknown12: SeString,
    pub r#unknown13: SeString,
    pub r#unknown14: SeString,
    pub r#unknown15: SeString,
    pub r#unknown16: SeString,
    pub r#unknown17: SeString,
    pub r#unknown18: SeString,
    pub r#unknown19: SeString,
    pub r#unknown20: SeString,
    pub r#unknown21: SeString,
    pub r#unknown22: SeString,
    pub r#unknown23: SeString,
    pub r#unknown24: SeString,
    pub r#unknown25: SeString,
    pub r#unknown26: SeString,
    pub r#unknown27: SeString,
    pub r#unknown28: SeString,
    pub r#unknown29: SeString,
    pub r#unknown30: SeString,
    pub r#unknown31: SeString,
    pub r#unknown32: SeString,
    pub r#unknown33: SeString,
    pub r#unknown34: SeString,
    pub r#unknown35: SeString,
    pub r#unknown36: SeString,
    pub r#unknown37: SeString,
    pub r#unknown38: SeString,
    pub r#unknown39: SeString,
    pub r#unknown40: SeString,
    pub r#unknown41: SeString,
    pub r#unknown42: u32,
    pub r#unknown43: u32,
    pub r#unknown44: u32,
    pub r#unknown45: u32,
    pub r#unknown46: u32,
    pub r#unknown47: u32,
    pub r#unknown48: u32,
    pub r#unknown49: u32,
    pub r#unknown50: u32,
    pub r#unknown51: u32,
    pub r#unknown52: u32,
    pub r#unknown53: u32,
    pub r#unknown54: u32,
    pub r#unknown55: u32,
    pub r#unknown56: u32,
    pub r#unknown57: u32,
    pub r#unknown58: u32,
    pub r#unknown59: u32,
    pub r#unknown60: u32,
    pub r#unknown61: u32,
    pub r#unknown62: u32,
    pub r#unknown63: u32,
    pub r#unknown64: u32,
    pub r#unknown65: u32,
    pub r#unknown66: u32,
    pub r#unknown67: u32,
    pub r#unknown68: u32,
    pub r#unknown69: u32,
    pub r#unknown70: u32,
    pub r#unknown71: u32,
    pub r#unknown72: u32,
    pub r#unknown73: u32,
    pub r#unknown74: u32,
    pub r#unknown75: u32,
    pub r#unknown76: u32,
    pub r#unknown77: u32,
    pub r#unknown78: u32,
    pub r#unknown79: u32,
    pub r#unknown80: u32,
    pub r#unknown81: u32,
}
impl Opening {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#name: row.field(0usize + offset)?.into_string()?,
            r#quest: row.field(1usize + offset)?.into_u32()?,
            r#unknown2: row.field(2usize + offset)?.into_string()?,
            r#unknown3: row.field(3usize + offset)?.into_string()?,
            r#unknown4: row.field(4usize + offset)?.into_string()?,
            r#unknown5: row.field(5usize + offset)?.into_string()?,
            r#unknown6: row.field(6usize + offset)?.into_string()?,
            r#unknown7: row.field(7usize + offset)?.into_string()?,
            r#unknown8: row.field(8usize + offset)?.into_string()?,
            r#unknown9: row.field(9usize + offset)?.into_string()?,
            r#unknown10: row.field(10usize + offset)?.into_string()?,
            r#unknown11: row.field(11usize + offset)?.into_string()?,
            r#unknown12: row.field(12usize + offset)?.into_string()?,
            r#unknown13: row.field(13usize + offset)?.into_string()?,
            r#unknown14: row.field(14usize + offset)?.into_string()?,
            r#unknown15: row.field(15usize + offset)?.into_string()?,
            r#unknown16: row.field(16usize + offset)?.into_string()?,
            r#unknown17: row.field(17usize + offset)?.into_string()?,
            r#unknown18: row.field(18usize + offset)?.into_string()?,
            r#unknown19: row.field(19usize + offset)?.into_string()?,
            r#unknown20: row.field(20usize + offset)?.into_string()?,
            r#unknown21: row.field(21usize + offset)?.into_string()?,
            r#unknown22: row.field(22usize + offset)?.into_string()?,
            r#unknown23: row.field(23usize + offset)?.into_string()?,
            r#unknown24: row.field(24usize + offset)?.into_string()?,
            r#unknown25: row.field(25usize + offset)?.into_string()?,
            r#unknown26: row.field(26usize + offset)?.into_string()?,
            r#unknown27: row.field(27usize + offset)?.into_string()?,
            r#unknown28: row.field(28usize + offset)?.into_string()?,
            r#unknown29: row.field(29usize + offset)?.into_string()?,
            r#unknown30: row.field(30usize + offset)?.into_string()?,
            r#unknown31: row.field(31usize + offset)?.into_string()?,
            r#unknown32: row.field(32usize + offset)?.into_string()?,
            r#unknown33: row.field(33usize + offset)?.into_string()?,
            r#unknown34: row.field(34usize + offset)?.into_string()?,
            r#unknown35: row.field(35usize + offset)?.into_string()?,
            r#unknown36: row.field(36usize + offset)?.into_string()?,
            r#unknown37: row.field(37usize + offset)?.into_string()?,
            r#unknown38: row.field(38usize + offset)?.into_string()?,
            r#unknown39: row.field(39usize + offset)?.into_string()?,
            r#unknown40: row.field(40usize + offset)?.into_string()?,
            r#unknown41: row.field(41usize + offset)?.into_string()?,
            r#unknown42: row.field(42usize + offset)?.into_u32()?,
            r#unknown43: row.field(43usize + offset)?.into_u32()?,
            r#unknown44: row.field(44usize + offset)?.into_u32()?,
            r#unknown45: row.field(45usize + offset)?.into_u32()?,
            r#unknown46: row.field(46usize + offset)?.into_u32()?,
            r#unknown47: row.field(47usize + offset)?.into_u32()?,
            r#unknown48: row.field(48usize + offset)?.into_u32()?,
            r#unknown49: row.field(49usize + offset)?.into_u32()?,
            r#unknown50: row.field(50usize + offset)?.into_u32()?,
            r#unknown51: row.field(51usize + offset)?.into_u32()?,
            r#unknown52: row.field(52usize + offset)?.into_u32()?,
            r#unknown53: row.field(53usize + offset)?.into_u32()?,
            r#unknown54: row.field(54usize + offset)?.into_u32()?,
            r#unknown55: row.field(55usize + offset)?.into_u32()?,
            r#unknown56: row.field(56usize + offset)?.into_u32()?,
            r#unknown57: row.field(57usize + offset)?.into_u32()?,
            r#unknown58: row.field(58usize + offset)?.into_u32()?,
            r#unknown59: row.field(59usize + offset)?.into_u32()?,
            r#unknown60: row.field(60usize + offset)?.into_u32()?,
            r#unknown61: row.field(61usize + offset)?.into_u32()?,
            r#unknown62: row.field(62usize + offset)?.into_u32()?,
            r#unknown63: row.field(63usize + offset)?.into_u32()?,
            r#unknown64: row.field(64usize + offset)?.into_u32()?,
            r#unknown65: row.field(65usize + offset)?.into_u32()?,
            r#unknown66: row.field(66usize + offset)?.into_u32()?,
            r#unknown67: row.field(67usize + offset)?.into_u32()?,
            r#unknown68: row.field(68usize + offset)?.into_u32()?,
            r#unknown69: row.field(69usize + offset)?.into_u32()?,
            r#unknown70: row.field(70usize + offset)?.into_u32()?,
            r#unknown71: row.field(71usize + offset)?.into_u32()?,
            r#unknown72: row.field(72usize + offset)?.into_u32()?,
            r#unknown73: row.field(73usize + offset)?.into_u32()?,
            r#unknown74: row.field(74usize + offset)?.into_u32()?,
            r#unknown75: row.field(75usize + offset)?.into_u32()?,
            r#unknown76: row.field(76usize + offset)?.into_u32()?,
            r#unknown77: row.field(77usize + offset)?.into_u32()?,
            r#unknown78: row.field(78usize + offset)?.into_u32()?,
            r#unknown79: row.field(79usize + offset)?.into_u32()?,
            r#unknown80: row.field(80usize + offset)?.into_u32()?,
            r#unknown81: row.field(81usize + offset)?.into_u32()?,
        })
    }
}
