use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use ironworks::excel::Row;
use ironworks::sestring::SeString;
use std::result::Result;
impl MetadataAdapter for PetMirage {
    fn name() -> String {
        "PetMirage".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(PetMirage::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct PetMirage {
    pub r#unknown0: f32,
    pub r#unknown1: u16,
    pub r#name: SeString,
    pub r#unknown3: u16,
    pub r#unknown4: u16,
    pub r#unknown5: u16,
    pub r#unknown6: u16,
    pub r#unknown7: u16,
    pub r#unknown8: u16,
    pub r#unknown9: u16,
    pub r#unknown10: u16,
    pub r#unknown11: u16,
    pub r#unknown12: u16,
    pub r#unknown13: u16,
    pub r#unknown14: u16,
    pub r#unknown15: u16,
    pub r#unknown16: u16,
    pub r#unknown17: u16,
    pub r#unknown18: u8,
    pub r#unknown19: u8,
    pub r#unknown20: u8,
    pub r#unknown21: u8,
    pub r#unknown22: u8,
    pub r#unknown23: u8,
    pub r#unknown24: u8,
    pub r#unknown25: u8,
    pub r#unknown26: u8,
    pub r#unknown27: u8,
    pub r#unknown28: u8,
    pub r#unknown29: u8,
    pub r#unknown30: u8,
    pub r#unknown31: u8,
    pub r#unknown32: u8,
    pub r#unknown33: u16,
    pub r#unknown34: u16,
    pub r#unknown35: u16,
    pub r#unknown36: u16,
    pub r#unknown37: u16,
    pub r#unknown38: u16,
    pub r#unknown39: u16,
    pub r#unknown40: u16,
    pub r#unknown41: u16,
    pub r#unknown42: u16,
    pub r#unknown43: u16,
    pub r#unknown44: u16,
    pub r#unknown45: u16,
    pub r#unknown46: u16,
    pub r#unknown47: u16,
    pub r#unknown48: u16,
    pub r#unknown49: u16,
    pub r#unknown50: u16,
    pub r#unknown51: u16,
    pub r#unknown52: u16,
    pub r#unknown53: u16,
    pub r#unknown54: u16,
    pub r#unknown55: u16,
    pub r#unknown56: u16,
    pub r#unknown57: u16,
    pub r#unknown58: u16,
    pub r#unknown59: u16,
    pub r#unknown60: u16,
    pub r#unknown61: u16,
    pub r#unknown62: u16,
}
impl PetMirage {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#unknown0: row.field(0usize + offset)?.into_f32()?,
            r#unknown1: row.field(1usize + offset)?.into_u16()?,
            r#name: row.field(2usize + offset)?.into_string()?,
            r#unknown3: row.field(3usize + offset)?.into_u16()?,
            r#unknown4: row.field(4usize + offset)?.into_u16()?,
            r#unknown5: row.field(5usize + offset)?.into_u16()?,
            r#unknown6: row.field(6usize + offset)?.into_u16()?,
            r#unknown7: row.field(7usize + offset)?.into_u16()?,
            r#unknown8: row.field(8usize + offset)?.into_u16()?,
            r#unknown9: row.field(9usize + offset)?.into_u16()?,
            r#unknown10: row.field(10usize + offset)?.into_u16()?,
            r#unknown11: row.field(11usize + offset)?.into_u16()?,
            r#unknown12: row.field(12usize + offset)?.into_u16()?,
            r#unknown13: row.field(13usize + offset)?.into_u16()?,
            r#unknown14: row.field(14usize + offset)?.into_u16()?,
            r#unknown15: row.field(15usize + offset)?.into_u16()?,
            r#unknown16: row.field(16usize + offset)?.into_u16()?,
            r#unknown17: row.field(17usize + offset)?.into_u16()?,
            r#unknown18: row.field(18usize + offset)?.into_u8()?,
            r#unknown19: row.field(19usize + offset)?.into_u8()?,
            r#unknown20: row.field(20usize + offset)?.into_u8()?,
            r#unknown21: row.field(21usize + offset)?.into_u8()?,
            r#unknown22: row.field(22usize + offset)?.into_u8()?,
            r#unknown23: row.field(23usize + offset)?.into_u8()?,
            r#unknown24: row.field(24usize + offset)?.into_u8()?,
            r#unknown25: row.field(25usize + offset)?.into_u8()?,
            r#unknown26: row.field(26usize + offset)?.into_u8()?,
            r#unknown27: row.field(27usize + offset)?.into_u8()?,
            r#unknown28: row.field(28usize + offset)?.into_u8()?,
            r#unknown29: row.field(29usize + offset)?.into_u8()?,
            r#unknown30: row.field(30usize + offset)?.into_u8()?,
            r#unknown31: row.field(31usize + offset)?.into_u8()?,
            r#unknown32: row.field(32usize + offset)?.into_u8()?,
            r#unknown33: row.field(33usize + offset)?.into_u16()?,
            r#unknown34: row.field(34usize + offset)?.into_u16()?,
            r#unknown35: row.field(35usize + offset)?.into_u16()?,
            r#unknown36: row.field(36usize + offset)?.into_u16()?,
            r#unknown37: row.field(37usize + offset)?.into_u16()?,
            r#unknown38: row.field(38usize + offset)?.into_u16()?,
            r#unknown39: row.field(39usize + offset)?.into_u16()?,
            r#unknown40: row.field(40usize + offset)?.into_u16()?,
            r#unknown41: row.field(41usize + offset)?.into_u16()?,
            r#unknown42: row.field(42usize + offset)?.into_u16()?,
            r#unknown43: row.field(43usize + offset)?.into_u16()?,
            r#unknown44: row.field(44usize + offset)?.into_u16()?,
            r#unknown45: row.field(45usize + offset)?.into_u16()?,
            r#unknown46: row.field(46usize + offset)?.into_u16()?,
            r#unknown47: row.field(47usize + offset)?.into_u16()?,
            r#unknown48: row.field(48usize + offset)?.into_u16()?,
            r#unknown49: row.field(49usize + offset)?.into_u16()?,
            r#unknown50: row.field(50usize + offset)?.into_u16()?,
            r#unknown51: row.field(51usize + offset)?.into_u16()?,
            r#unknown52: row.field(52usize + offset)?.into_u16()?,
            r#unknown53: row.field(53usize + offset)?.into_u16()?,
            r#unknown54: row.field(54usize + offset)?.into_u16()?,
            r#unknown55: row.field(55usize + offset)?.into_u16()?,
            r#unknown56: row.field(56usize + offset)?.into_u16()?,
            r#unknown57: row.field(57usize + offset)?.into_u16()?,
            r#unknown58: row.field(58usize + offset)?.into_u16()?,
            r#unknown59: row.field(59usize + offset)?.into_u16()?,
            r#unknown60: row.field(60usize + offset)?.into_u16()?,
            r#unknown61: row.field(61usize + offset)?.into_u16()?,
            r#unknown62: row.field(62usize + offset)?.into_u16()?,
        })
    }
}
