use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use crate::utility::read_array;
use ironworks::excel::Row;
use ironworks::sestring::SeString;
use std::result::Result;
use std::vec::Vec;
impl MetadataAdapter for Quest {
    fn name() -> String {
        "Quest".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(Quest::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct Quest {
    pub r#name: SeString,
    pub r#id: SeString,
    pub r#expansion: u8,
    pub r#class_job_category0: u8,
    pub r#class_job_level0: u16,
    pub r#quest_level_offset: u8,
    pub r#class_job_category1: u8,
    pub r#class_job_level1: u16,
    pub r#previous_quest_join: u8,
    pub r#previous_quest: Vec<u32>,
    pub r#quest_lock_join: u8,
    pub r#quest_lock: Vec<u32>,
    pub r#header: u16,
    pub r#unknown17: u8,
    pub r#unknown18: u8,
    pub r#class_job_unlock: u8,
    pub r#grand_company: u8,
    pub r#grand_company_rank: u8,
    pub r#instance_content_join: u8,
    pub r#instance_content: Vec<u32>,
    pub r#festival: u16,
    pub r#festival_begin: u8,
    pub r#festival_end: u8,
    pub r#bell_start: u16,
    pub r#bell_end: u16,
    pub r#beast_tribe: u8,
    pub r#beast_reputation_rank: u8,
    pub r#beast_reputation_value: u16,
    pub r#satisfaction_npc: u8,
    pub r#satisfaction_level: u8,
    pub r#mount_required: i32,
    pub r#is_house_required: bool,
    pub r#delivery_quest: u8,
    pub r#issuer_start: u32,
    pub r#issuer_location: u32,
    pub r#client_behavior: u16,
    pub r#target_end: u32,
    pub r#is_repeatable: bool,
    pub r#repeat_interval_type: u8,
    pub r#quest_repeat_flag: u8,
    pub r#can_cancel: bool,
    pub r#type: u8,
    pub r#quest_class_job_supply: u16,
    pub r#unknown49: u8,
    pub r#script_instruction: Vec<SeString>,
    pub r#script_arg: Vec<u32>,
    pub r#actor_spawn_seq: Vec<u8>,
    pub r#actor_despawn_seq: Vec<u8>,
    pub r#listener: Vec<u8>,
    pub r#quest_u_int8_a: Vec<u8>,
    pub r#quest_u_int8_b: Vec<u8>,
    pub r#condition_type: Vec<u32>,
    pub r#condition_value: Vec<u8>,
    pub r#condition_operator: Vec<u8>,
    pub r#behavior: Vec<u32>,
    pub r#visible_bool: Vec<u8>,
    pub r#condition_bool: Vec<u16>,
    pub r#item_bool: Vec<bool>,
    pub r#announce_bool: Vec<bool>,
    pub r#behavior_bool: Vec<bool>,
    pub r#accept_bool: Vec<bool>,
    pub r#qualified_bool: Vec<bool>,
    pub r#can_target_bool: Vec<bool>,
    pub r#to_do_complete_seq: Vec<bool>,
    pub r#to_do_qty: Vec<bool>,
    pub r#to_do_location: Vec<Vec<bool>>,
    pub r#countable_num: Vec<u32>,
    pub r#level_max: u32,
    pub r#class_job_required: u32,
    pub r#quest_reward_other_display: u32,
    pub r#exp_factor: u32,
    pub r#gil_reward: u32,
    pub r#currency_reward: u32,
    pub r#currency_reward_count: u32,
    pub r#item_catalyst: Vec<u32>,
    pub r#item_count_catalyst: Vec<u32>,
    pub r#item_reward_type: u32,
    pub r#item_reward: Vec<u32>,
    pub r#item_count_reward: Vec<u32>,
    pub r#unknown1466: u32,
    pub r#unknown1467: u32,
    pub r#unknown1468: u32,
    pub r#unknown1469: u32,
    pub r#unknown1470: u32,
    pub r#unknown1471: u32,
    pub r#unknown1472: u32,
    pub r#stain_reward: Vec<u32>,
    pub r#optional_item_reward: Vec<u32>,
    pub r#optional_item_count_reward: Vec<u32>,
    pub r#optional_item_is_hq_reward: Vec<u32>,
    pub r#optional_item_stain_reward: Vec<u32>,
    pub r#emote_reward: u32,
    pub r#action_reward: u32,
    pub r#general_action_reward: Vec<u32>,
    pub r#system_reward0: u32,
    pub r#other_reward: u32,
    pub r#system_reward1: u32,
    pub r#gc_type_reward: u32,
    pub r#instance_content_unlock: u32,
    pub r#tomestone: u32,
    pub r#tomestone_reward: u32,
    pub r#tomestone_count_reward: u32,
    pub r#reputation_reward: u32,
    pub r#place_name: u32,
    pub r#journal_genre: u32,
    pub r#unknown1515: u32,
    pub r#icon: u32,
    pub r#icon_special: u32,
    pub r#introduction: u32,
    pub r#hide_offer_icon: u32,
    pub r#event_icon_type: u32,
    pub r#unknown1521: u32,
    pub r#sort_key: u32,
    pub r#unknown1523: u32,
    pub r#unknown1524: u32,
    pub r#unknown1525: u32,
    pub r#unknown1526: u32,
    pub r#unknown1527: u32,
    pub r#unknown1528: u32,
    pub r#unknown1529: u32,
    pub r#unknown1530: u32,
    pub r#unknown1531: u32,
    pub r#unknown1532: u32,
    pub r#unknown1533: u32,
    pub r#unknown1534: u32,
    pub r#unknown1535: u32,
    pub r#unknown1536: u32,
    pub r#unknown1537: u32,
    pub r#unknown1538: u32,
    pub r#unknown1539: u32,
    pub r#unknown1540: u32,
    pub r#unknown1541: u32,
    pub r#unknown1542: u8,
    pub r#unknown1543: u8,
    pub r#unknown1544: u8,
    pub r#unknown1545: u8,
    pub r#unknown1546: u8,
    pub r#unknown1547: u8,
    pub r#unknown1548: u8,
    pub r#unknown1549: u8,
    pub r#unknown1550: u8,
    pub r#unknown1551: u8,
    pub r#unknown1552: u8,
    pub r#unknown1553: u8,
    pub r#unknown1554: u8,
    pub r#unknown1555: u8,
    pub r#unknown1556: u8,
    pub r#unknown1557: u8,
    pub r#unknown1558: u8,
    pub r#unknown1559: u8,
    pub r#unknown1560: u8,
    pub r#unknown1561: u8,
    pub r#unknown1562: u8,
    pub r#unknown1563: u8,
    pub r#unknown1564: u8,
    pub r#unknown1565: u8,
    pub r#unknown1566: u8,
    pub r#unknown1567: u8,
    pub r#unknown1568: u8,
    pub r#unknown1569: u16,
    pub r#unknown1570: u32,
    pub r#unknown1571: u32,
    pub r#unknown1572: u32,
    pub r#unknown1573: u8,
    pub r#unknown1574: u8,
    pub r#unknown1575: u8,
    pub r#unknown1576: u8,
    pub r#unknown1577: u8,
    pub r#unknown1578: u8,
    pub r#unknown1579: u8,
    pub r#unknown1580: u32,
    pub r#unknown1581: u32,
    pub r#unknown1582: u32,
    pub r#unknown1583: u32,
    pub r#unknown1584: u32,
    pub r#unknown1585: u32,
    pub r#unknown1586: u32,
    pub r#unknown1587: u8,
    pub r#unknown1588: u8,
    pub r#unknown1589: u8,
    pub r#unknown1590: u8,
    pub r#unknown1591: u8,
    pub r#unknown1592: u8,
    pub r#unknown1593: u8,
    pub r#unknown1594: bool,
    pub r#unknown1595: bool,
    pub r#unknown1596: bool,
    pub r#unknown1597: bool,
    pub r#unknown1598: bool,
    pub r#unknown1599: bool,
    pub r#unknown1600: bool,
    pub r#unknown1601: u8,
    pub r#unknown1602: u8,
    pub r#unknown1603: u8,
    pub r#unknown1604: u8,
    pub r#unknown1605: u8,
    pub r#unknown1606: u8,
    pub r#unknown1607: u8,
    pub r#unknown1608: u32,
    pub r#unknown1609: u32,
    pub r#unknown1610: u32,
    pub r#unknown1611: u32,
    pub r#unknown1612: u32,
    pub r#unknown1613: u8,
    pub r#unknown1614: u8,
    pub r#unknown1615: u8,
    pub r#unknown1616: u8,
    pub r#unknown1617: u8,
    pub r#unknown1618: bool,
    pub r#unknown1619: bool,
    pub r#unknown1620: bool,
    pub r#unknown1621: bool,
    pub r#unknown1622: bool,
    pub r#unknown1623: u8,
    pub r#unknown1624: u8,
    pub r#unknown1625: u8,
    pub r#unknown1626: u8,
    pub r#unknown1627: u8,
    pub r#unknown1628: u16,
    pub r#unknown1629: u16,
    pub r#unknown1630: u8,
    pub r#unknown1631: u8,
    pub r#unknown1632: u16,
    pub r#unknown1633: u8,
    pub r#unknown1634: u16,
    pub r#unknown1635: u16,
    pub r#unknown1636: u32,
    pub r#unknown1637: u8,
    pub r#unknown1638: u8,
    pub r#unknown1639: u8,
    pub r#unknown1640: u8,
    pub r#unknown1641: u16,
    pub r#unknown1642: u32,
    pub r#unknown1643: u8,
    pub r#unknown1644: u32,
    pub r#unknown1645: u32,
    pub r#unknown1646: bool,
    pub r#unknown1647: bool,
    pub r#unknown1648: u8,
    pub r#unknown1649: u8,
    pub r#unknown1650: u16,
    pub r#unknown1651: bool,
    pub r#unknown1652: bool,
}
impl Quest {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#name: row.field(0usize + offset)?.into_string()?,
            r#id: row.field(1usize + offset)?.into_string()?,
            r#expansion: row.field(2usize + offset)?.into_u8()?,
            r#class_job_category0: row.field(3usize + offset)?.into_u8()?,
            r#class_job_level0: row.field(4usize + offset)?.into_u16()?,
            r#quest_level_offset: row.field(5usize + offset)?.into_u8()?,
            r#class_job_category1: row.field(6usize + offset)?.into_u8()?,
            r#class_job_level1: row.field(7usize + offset)?.into_u16()?,
            r#previous_quest_join: row.field(8usize + offset)?.into_u8()?,
            r#previous_quest: read_array(
                offset,
                4usize,
                1usize,
                |offset| { Result::Ok(row.field(9usize + offset)?.into_u32()?) },
            )?,
            r#quest_lock_join: row.field(13usize + offset)?.into_u8()?,
            r#quest_lock: read_array(
                offset,
                2usize,
                1usize,
                |offset| { Result::Ok(row.field(14usize + offset)?.into_u32()?) },
            )?,
            r#header: row.field(16usize + offset)?.into_u16()?,
            r#unknown17: row.field(17usize + offset)?.into_u8()?,
            r#unknown18: row.field(18usize + offset)?.into_u8()?,
            r#class_job_unlock: row.field(19usize + offset)?.into_u8()?,
            r#grand_company: row.field(20usize + offset)?.into_u8()?,
            r#grand_company_rank: row.field(21usize + offset)?.into_u8()?,
            r#instance_content_join: row.field(22usize + offset)?.into_u8()?,
            r#instance_content: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(23usize + offset)?.into_u32()?) },
            )?,
            r#festival: row.field(26usize + offset)?.into_u16()?,
            r#festival_begin: row.field(27usize + offset)?.into_u8()?,
            r#festival_end: row.field(28usize + offset)?.into_u8()?,
            r#bell_start: row.field(29usize + offset)?.into_u16()?,
            r#bell_end: row.field(30usize + offset)?.into_u16()?,
            r#beast_tribe: row.field(31usize + offset)?.into_u8()?,
            r#beast_reputation_rank: row.field(32usize + offset)?.into_u8()?,
            r#beast_reputation_value: row.field(33usize + offset)?.into_u16()?,
            r#satisfaction_npc: row.field(34usize + offset)?.into_u8()?,
            r#satisfaction_level: row.field(35usize + offset)?.into_u8()?,
            r#mount_required: row.field(36usize + offset)?.into_i32()?,
            r#is_house_required: row.field(37usize + offset)?.into_bool()?,
            r#delivery_quest: row.field(38usize + offset)?.into_u8()?,
            r#issuer_start: row.field(39usize + offset)?.into_u32()?,
            r#issuer_location: row.field(40usize + offset)?.into_u32()?,
            r#client_behavior: row.field(41usize + offset)?.into_u16()?,
            r#target_end: row.field(42usize + offset)?.into_u32()?,
            r#is_repeatable: row.field(43usize + offset)?.into_bool()?,
            r#repeat_interval_type: row.field(44usize + offset)?.into_u8()?,
            r#quest_repeat_flag: row.field(45usize + offset)?.into_u8()?,
            r#can_cancel: row.field(46usize + offset)?.into_bool()?,
            r#type: row.field(47usize + offset)?.into_u8()?,
            r#quest_class_job_supply: row.field(48usize + offset)?.into_u16()?,
            r#unknown49: row.field(49usize + offset)?.into_u8()?,
            r#script_instruction: read_array(
                offset,
                50usize,
                1usize,
                |offset| { Result::Ok(row.field(50usize + offset)?.into_string()?) },
            )?,
            r#script_arg: read_array(
                offset,
                50usize,
                1usize,
                |offset| { Result::Ok(row.field(100usize + offset)?.into_u32()?) },
            )?,
            r#actor_spawn_seq: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(150usize + offset)?.into_u8()?) },
            )?,
            r#actor_despawn_seq: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(214usize + offset)?.into_u8()?) },
            )?,
            r#listener: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(278usize + offset)?.into_u8()?) },
            )?,
            r#quest_u_int8_a: read_array(
                offset,
                32usize,
                1usize,
                |offset| { Result::Ok(row.field(342usize + offset)?.into_u8()?) },
            )?,
            r#quest_u_int8_b: read_array(
                offset,
                32usize,
                1usize,
                |offset| { Result::Ok(row.field(374usize + offset)?.into_u8()?) },
            )?,
            r#condition_type: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(406usize + offset)?.into_u32()?) },
            )?,
            r#condition_value: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(470usize + offset)?.into_u8()?) },
            )?,
            r#condition_operator: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(534usize + offset)?.into_u8()?) },
            )?,
            r#behavior: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(598usize + offset)?.into_u32()?) },
            )?,
            r#visible_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(662usize + offset)?.into_u8()?) },
            )?,
            r#condition_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(726usize + offset)?.into_u16()?) },
            )?,
            r#item_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(790usize + offset)?.into_bool()?) },
            )?,
            r#announce_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(854usize + offset)?.into_bool()?) },
            )?,
            r#behavior_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(918usize + offset)?.into_bool()?) },
            )?,
            r#accept_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(982usize + offset)?.into_bool()?) },
            )?,
            r#qualified_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(1046usize + offset)?.into_bool()?) },
            )?,
            r#can_target_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(1110usize + offset)?.into_bool()?) },
            )?,
            r#to_do_complete_seq: read_array(
                offset,
                24usize,
                1usize,
                |offset| { Result::Ok(row.field(1174usize + offset)?.into_bool()?) },
            )?,
            r#to_do_qty: read_array(
                offset,
                24usize,
                1usize,
                |offset| { Result::Ok(row.field(1198usize + offset)?.into_bool()?) },
            )?,
            r#to_do_location: read_array(
                offset,
                8usize,
                24usize,
                |offset| {
                    Result::Ok(
                        read_array(
                            offset,
                            24usize,
                            1usize,
                            |offset| {
                                Result::Ok(row.field(1222usize + offset)?.into_bool()?)
                            },
                        )?,
                    )
                },
            )?,
            r#countable_num: read_array(
                offset,
                24usize,
                1usize,
                |offset| { Result::Ok(row.field(1414usize + offset)?.into_u32()?) },
            )?,
            r#level_max: row.field(1438usize + offset)?.into_u32()?,
            r#class_job_required: row.field(1439usize + offset)?.into_u32()?,
            r#quest_reward_other_display: row.field(1440usize + offset)?.into_u32()?,
            r#exp_factor: row.field(1441usize + offset)?.into_u32()?,
            r#gil_reward: row.field(1442usize + offset)?.into_u32()?,
            r#currency_reward: row.field(1443usize + offset)?.into_u32()?,
            r#currency_reward_count: row.field(1444usize + offset)?.into_u32()?,
            r#item_catalyst: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(1445usize + offset)?.into_u32()?) },
            )?,
            r#item_count_catalyst: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(1448usize + offset)?.into_u32()?) },
            )?,
            r#item_reward_type: row.field(1451usize + offset)?.into_u32()?,
            r#item_reward: read_array(
                offset,
                7usize,
                1usize,
                |offset| { Result::Ok(row.field(1452usize + offset)?.into_u32()?) },
            )?,
            r#item_count_reward: read_array(
                offset,
                7usize,
                1usize,
                |offset| { Result::Ok(row.field(1459usize + offset)?.into_u32()?) },
            )?,
            r#unknown1466: row.field(1466usize + offset)?.into_u32()?,
            r#unknown1467: row.field(1467usize + offset)?.into_u32()?,
            r#unknown1468: row.field(1468usize + offset)?.into_u32()?,
            r#unknown1469: row.field(1469usize + offset)?.into_u32()?,
            r#unknown1470: row.field(1470usize + offset)?.into_u32()?,
            r#unknown1471: row.field(1471usize + offset)?.into_u32()?,
            r#unknown1472: row.field(1472usize + offset)?.into_u32()?,
            r#stain_reward: read_array(
                offset,
                7usize,
                1usize,
                |offset| { Result::Ok(row.field(1473usize + offset)?.into_u32()?) },
            )?,
            r#optional_item_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1480usize + offset)?.into_u32()?) },
            )?,
            r#optional_item_count_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1485usize + offset)?.into_u32()?) },
            )?,
            r#optional_item_is_hq_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1490usize + offset)?.into_u32()?) },
            )?,
            r#optional_item_stain_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1495usize + offset)?.into_u32()?) },
            )?,
            r#emote_reward: row.field(1500usize + offset)?.into_u32()?,
            r#action_reward: row.field(1501usize + offset)?.into_u32()?,
            r#general_action_reward: read_array(
                offset,
                2usize,
                1usize,
                |offset| { Result::Ok(row.field(1502usize + offset)?.into_u32()?) },
            )?,
            r#system_reward0: row.field(1504usize + offset)?.into_u32()?,
            r#other_reward: row.field(1505usize + offset)?.into_u32()?,
            r#system_reward1: row.field(1506usize + offset)?.into_u32()?,
            r#gc_type_reward: row.field(1507usize + offset)?.into_u32()?,
            r#instance_content_unlock: row.field(1508usize + offset)?.into_u32()?,
            r#tomestone: row.field(1509usize + offset)?.into_u32()?,
            r#tomestone_reward: row.field(1510usize + offset)?.into_u32()?,
            r#tomestone_count_reward: row.field(1511usize + offset)?.into_u32()?,
            r#reputation_reward: row.field(1512usize + offset)?.into_u32()?,
            r#place_name: row.field(1513usize + offset)?.into_u32()?,
            r#journal_genre: row.field(1514usize + offset)?.into_u32()?,
            r#unknown1515: row.field(1515usize + offset)?.into_u32()?,
            r#icon: row.field(1516usize + offset)?.into_u32()?,
            r#icon_special: row.field(1517usize + offset)?.into_u32()?,
            r#introduction: row.field(1518usize + offset)?.into_u32()?,
            r#hide_offer_icon: row.field(1519usize + offset)?.into_u32()?,
            r#event_icon_type: row.field(1520usize + offset)?.into_u32()?,
            r#unknown1521: row.field(1521usize + offset)?.into_u32()?,
            r#sort_key: row.field(1522usize + offset)?.into_u32()?,
            r#unknown1523: row.field(1523usize + offset)?.into_u32()?,
            r#unknown1524: row.field(1524usize + offset)?.into_u32()?,
            r#unknown1525: row.field(1525usize + offset)?.into_u32()?,
            r#unknown1526: row.field(1526usize + offset)?.into_u32()?,
            r#unknown1527: row.field(1527usize + offset)?.into_u32()?,
            r#unknown1528: row.field(1528usize + offset)?.into_u32()?,
            r#unknown1529: row.field(1529usize + offset)?.into_u32()?,
            r#unknown1530: row.field(1530usize + offset)?.into_u32()?,
            r#unknown1531: row.field(1531usize + offset)?.into_u32()?,
            r#unknown1532: row.field(1532usize + offset)?.into_u32()?,
            r#unknown1533: row.field(1533usize + offset)?.into_u32()?,
            r#unknown1534: row.field(1534usize + offset)?.into_u32()?,
            r#unknown1535: row.field(1535usize + offset)?.into_u32()?,
            r#unknown1536: row.field(1536usize + offset)?.into_u32()?,
            r#unknown1537: row.field(1537usize + offset)?.into_u32()?,
            r#unknown1538: row.field(1538usize + offset)?.into_u32()?,
            r#unknown1539: row.field(1539usize + offset)?.into_u32()?,
            r#unknown1540: row.field(1540usize + offset)?.into_u32()?,
            r#unknown1541: row.field(1541usize + offset)?.into_u32()?,
            r#unknown1542: row.field(1542usize + offset)?.into_u8()?,
            r#unknown1543: row.field(1543usize + offset)?.into_u8()?,
            r#unknown1544: row.field(1544usize + offset)?.into_u8()?,
            r#unknown1545: row.field(1545usize + offset)?.into_u8()?,
            r#unknown1546: row.field(1546usize + offset)?.into_u8()?,
            r#unknown1547: row.field(1547usize + offset)?.into_u8()?,
            r#unknown1548: row.field(1548usize + offset)?.into_u8()?,
            r#unknown1549: row.field(1549usize + offset)?.into_u8()?,
            r#unknown1550: row.field(1550usize + offset)?.into_u8()?,
            r#unknown1551: row.field(1551usize + offset)?.into_u8()?,
            r#unknown1552: row.field(1552usize + offset)?.into_u8()?,
            r#unknown1553: row.field(1553usize + offset)?.into_u8()?,
            r#unknown1554: row.field(1554usize + offset)?.into_u8()?,
            r#unknown1555: row.field(1555usize + offset)?.into_u8()?,
            r#unknown1556: row.field(1556usize + offset)?.into_u8()?,
            r#unknown1557: row.field(1557usize + offset)?.into_u8()?,
            r#unknown1558: row.field(1558usize + offset)?.into_u8()?,
            r#unknown1559: row.field(1559usize + offset)?.into_u8()?,
            r#unknown1560: row.field(1560usize + offset)?.into_u8()?,
            r#unknown1561: row.field(1561usize + offset)?.into_u8()?,
            r#unknown1562: row.field(1562usize + offset)?.into_u8()?,
            r#unknown1563: row.field(1563usize + offset)?.into_u8()?,
            r#unknown1564: row.field(1564usize + offset)?.into_u8()?,
            r#unknown1565: row.field(1565usize + offset)?.into_u8()?,
            r#unknown1566: row.field(1566usize + offset)?.into_u8()?,
            r#unknown1567: row.field(1567usize + offset)?.into_u8()?,
            r#unknown1568: row.field(1568usize + offset)?.into_u8()?,
            r#unknown1569: row.field(1569usize + offset)?.into_u16()?,
            r#unknown1570: row.field(1570usize + offset)?.into_u32()?,
            r#unknown1571: row.field(1571usize + offset)?.into_u32()?,
            r#unknown1572: row.field(1572usize + offset)?.into_u32()?,
            r#unknown1573: row.field(1573usize + offset)?.into_u8()?,
            r#unknown1574: row.field(1574usize + offset)?.into_u8()?,
            r#unknown1575: row.field(1575usize + offset)?.into_u8()?,
            r#unknown1576: row.field(1576usize + offset)?.into_u8()?,
            r#unknown1577: row.field(1577usize + offset)?.into_u8()?,
            r#unknown1578: row.field(1578usize + offset)?.into_u8()?,
            r#unknown1579: row.field(1579usize + offset)?.into_u8()?,
            r#unknown1580: row.field(1580usize + offset)?.into_u32()?,
            r#unknown1581: row.field(1581usize + offset)?.into_u32()?,
            r#unknown1582: row.field(1582usize + offset)?.into_u32()?,
            r#unknown1583: row.field(1583usize + offset)?.into_u32()?,
            r#unknown1584: row.field(1584usize + offset)?.into_u32()?,
            r#unknown1585: row.field(1585usize + offset)?.into_u32()?,
            r#unknown1586: row.field(1586usize + offset)?.into_u32()?,
            r#unknown1587: row.field(1587usize + offset)?.into_u8()?,
            r#unknown1588: row.field(1588usize + offset)?.into_u8()?,
            r#unknown1589: row.field(1589usize + offset)?.into_u8()?,
            r#unknown1590: row.field(1590usize + offset)?.into_u8()?,
            r#unknown1591: row.field(1591usize + offset)?.into_u8()?,
            r#unknown1592: row.field(1592usize + offset)?.into_u8()?,
            r#unknown1593: row.field(1593usize + offset)?.into_u8()?,
            r#unknown1594: row.field(1594usize + offset)?.into_bool()?,
            r#unknown1595: row.field(1595usize + offset)?.into_bool()?,
            r#unknown1596: row.field(1596usize + offset)?.into_bool()?,
            r#unknown1597: row.field(1597usize + offset)?.into_bool()?,
            r#unknown1598: row.field(1598usize + offset)?.into_bool()?,
            r#unknown1599: row.field(1599usize + offset)?.into_bool()?,
            r#unknown1600: row.field(1600usize + offset)?.into_bool()?,
            r#unknown1601: row.field(1601usize + offset)?.into_u8()?,
            r#unknown1602: row.field(1602usize + offset)?.into_u8()?,
            r#unknown1603: row.field(1603usize + offset)?.into_u8()?,
            r#unknown1604: row.field(1604usize + offset)?.into_u8()?,
            r#unknown1605: row.field(1605usize + offset)?.into_u8()?,
            r#unknown1606: row.field(1606usize + offset)?.into_u8()?,
            r#unknown1607: row.field(1607usize + offset)?.into_u8()?,
            r#unknown1608: row.field(1608usize + offset)?.into_u32()?,
            r#unknown1609: row.field(1609usize + offset)?.into_u32()?,
            r#unknown1610: row.field(1610usize + offset)?.into_u32()?,
            r#unknown1611: row.field(1611usize + offset)?.into_u32()?,
            r#unknown1612: row.field(1612usize + offset)?.into_u32()?,
            r#unknown1613: row.field(1613usize + offset)?.into_u8()?,
            r#unknown1614: row.field(1614usize + offset)?.into_u8()?,
            r#unknown1615: row.field(1615usize + offset)?.into_u8()?,
            r#unknown1616: row.field(1616usize + offset)?.into_u8()?,
            r#unknown1617: row.field(1617usize + offset)?.into_u8()?,
            r#unknown1618: row.field(1618usize + offset)?.into_bool()?,
            r#unknown1619: row.field(1619usize + offset)?.into_bool()?,
            r#unknown1620: row.field(1620usize + offset)?.into_bool()?,
            r#unknown1621: row.field(1621usize + offset)?.into_bool()?,
            r#unknown1622: row.field(1622usize + offset)?.into_bool()?,
            r#unknown1623: row.field(1623usize + offset)?.into_u8()?,
            r#unknown1624: row.field(1624usize + offset)?.into_u8()?,
            r#unknown1625: row.field(1625usize + offset)?.into_u8()?,
            r#unknown1626: row.field(1626usize + offset)?.into_u8()?,
            r#unknown1627: row.field(1627usize + offset)?.into_u8()?,
            r#unknown1628: row.field(1628usize + offset)?.into_u16()?,
            r#unknown1629: row.field(1629usize + offset)?.into_u16()?,
            r#unknown1630: row.field(1630usize + offset)?.into_u8()?,
            r#unknown1631: row.field(1631usize + offset)?.into_u8()?,
            r#unknown1632: row.field(1632usize + offset)?.into_u16()?,
            r#unknown1633: row.field(1633usize + offset)?.into_u8()?,
            r#unknown1634: row.field(1634usize + offset)?.into_u16()?,
            r#unknown1635: row.field(1635usize + offset)?.into_u16()?,
            r#unknown1636: row.field(1636usize + offset)?.into_u32()?,
            r#unknown1637: row.field(1637usize + offset)?.into_u8()?,
            r#unknown1638: row.field(1638usize + offset)?.into_u8()?,
            r#unknown1639: row.field(1639usize + offset)?.into_u8()?,
            r#unknown1640: row.field(1640usize + offset)?.into_u8()?,
            r#unknown1641: row.field(1641usize + offset)?.into_u16()?,
            r#unknown1642: row.field(1642usize + offset)?.into_u32()?,
            r#unknown1643: row.field(1643usize + offset)?.into_u8()?,
            r#unknown1644: row.field(1644usize + offset)?.into_u32()?,
            r#unknown1645: row.field(1645usize + offset)?.into_u32()?,
            r#unknown1646: row.field(1646usize + offset)?.into_bool()?,
            r#unknown1647: row.field(1647usize + offset)?.into_bool()?,
            r#unknown1648: row.field(1648usize + offset)?.into_u8()?,
            r#unknown1649: row.field(1649usize + offset)?.into_u8()?,
            r#unknown1650: row.field(1650usize + offset)?.into_u16()?,
            r#unknown1651: row.field(1651usize + offset)?.into_bool()?,
            r#unknown1652: row.field(1652usize + offset)?.into_bool()?,
        })
    }
}
