use ironworks::sestring::SeString;
use std::result::Result;
use crate::utility::read_array;
use crate::metadata::MetadataAdapter;
use crate::error::PopulateError;
use ironworks::excel::Row;
use std::vec::Vec;
impl MetadataAdapter for Quest {
    fn name() -> String {
        "Quest".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(Quest::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct Quest {
    pub r#name: SeString,
    pub r#id: SeString,
    pub r#expansion: u8,
    pub r#class_job_category0: u8,
    pub r#class_job_level0: u16,
    pub r#quest_level_offset: u8,
    pub r#class_job_category1: u8,
    pub r#class_job_level1: u16,
    pub r#previous_quest_join: u8,
    pub r#previous_quest0: u32,
    pub r#unknown10: u8,
    pub r#previous_quest1: u32,
    pub r#previous_quest2: u32,
    pub r#quest_lock_join: u8,
    pub r#quest_lock: Vec<u32>,
    pub r#header: u16,
    pub r#unknown17: u8,
    pub r#unknown18: u8,
    pub r#class_job_unlock: u8,
    pub r#grand_company: u8,
    pub r#grand_company_rank: u8,
    pub r#instance_content_join: u8,
    pub r#instance_content: Vec<u32>,
    pub r#festival: u8,
    pub r#festival_begin: u8,
    pub r#festival_end: u8,
    pub r#bell_start: u16,
    pub r#bell_end: u16,
    pub r#beast_tribe: u8,
    pub r#beast_reputation_rank: u8,
    pub r#beast_reputation_value: u16,
    pub r#satisfaction_npc: u8,
    pub r#satisfaction_level: u8,
    pub r#mount_required: i32,
    pub r#is_house_required: bool,
    pub r#delivery_quest: u8,
    pub r#issuer_start: u32,
    pub r#issuer_location: u32,
    pub r#client_behavior: u16,
    pub r#target_end: u32,
    pub r#is_repeatable: bool,
    pub r#repeat_interval_type: u8,
    pub r#quest_repeat_flag: u8,
    pub r#can_cancel: bool,
    pub r#type: u8,
    pub r#quest_class_job_supply: u16,
    pub r#script_instruction: Vec<SeString>,
    pub r#script_arg: Vec<u32>,
    pub r#actor_spawn_seq: Vec<u8>,
    pub r#actor_despawn_seq: Vec<u8>,
    pub r#listener: Vec<u32>,
    pub r#quest_u_int8_a: Vec<u8>,
    pub r#quest_u_int8_b: Vec<u8>,
    pub r#condition_type: Vec<u8>,
    pub r#condition_value: Vec<u32>,
    pub r#condition_operator: Vec<u8>,
    pub r#behavior: Vec<u16>,
    pub r#visible_bool: Vec<bool>,
    pub r#condition_bool: Vec<bool>,
    pub r#item_bool: Vec<bool>,
    pub r#announce_bool: Vec<bool>,
    pub r#behavior_bool: Vec<bool>,
    pub r#accept_bool: Vec<bool>,
    pub r#qualified_bool: Vec<bool>,
    pub r#can_target_bool: Vec<bool>,
    pub r#to_do_complete_seq: Vec<u8>,
    pub r#to_do_qty: Vec<u8>,
    pub r#to_do_main_location: Vec<u32>,
    pub r#to_do_child_location: Vec<Vec<u32>>,
    pub r#countable_num: Vec<u8>,
    pub r#level_max: u8,
    pub r#class_job_required: u8,
    pub r#quest_reward_other_display: u8,
    pub r#exp_factor: u16,
    pub r#gil_reward: u32,
    pub r#currency_reward: u32,
    pub r#currency_reward_count: u32,
    pub r#item_catalyst: Vec<u8>,
    pub r#item_count_catalyst: Vec<u8>,
    pub r#item_reward_type: u8,
    pub r#item_reward: Vec<u32>,
    pub r#item_count_reward: Vec<u8>,
    pub r#unknown1465: bool,
    pub r#unknown1466: bool,
    pub r#unknown1467: bool,
    pub r#unknown1468: bool,
    pub r#unknown1469: bool,
    pub r#unknown1470: bool,
    pub r#unknown1471: bool,
    pub r#stain_reward: Vec<u8>,
    pub r#optional_item_reward: Vec<u32>,
    pub r#optional_item_count_reward: Vec<u8>,
    pub r#optional_item_is_hq_reward: Vec<bool>,
    pub r#optional_item_stain_reward: Vec<u8>,
    pub r#emote_reward: u8,
    pub r#action_reward: u16,
    pub r#general_action_reward: Vec<u8>,
    pub r#system_reward0: u16,
    pub r#other_reward: u8,
    pub r#system_reward1: u16,
    pub r#gc_type_reward: u16,
    pub r#instance_content_unlock: u32,
    pub r#tomestone: u8,
    pub r#tomestone_reward: u8,
    pub r#tomestone_count_reward: u8,
    pub r#reputation_reward: u8,
    pub r#place_name: u16,
    pub r#journal_genre: u8,
    pub r#unknown1514: u8,
    pub r#icon: u32,
    pub r#icon_special: u32,
    pub r#introduction: bool,
    pub r#hide_offer_icon: bool,
    pub r#event_icon_type: u8,
    pub r#unknown1520: u8,
    pub r#sort_key: u16,
}
impl Quest {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#name: row.field(0usize + offset)?.into_string()?,
            r#id: row.field(1usize + offset)?.into_string()?,
            r#expansion: row.field(2usize + offset)?.into_u8()?,
            r#class_job_category0: row.field(3usize + offset)?.into_u8()?,
            r#class_job_level0: row.field(4usize + offset)?.into_u16()?,
            r#quest_level_offset: row.field(5usize + offset)?.into_u8()?,
            r#class_job_category1: row.field(6usize + offset)?.into_u8()?,
            r#class_job_level1: row.field(7usize + offset)?.into_u16()?,
            r#previous_quest_join: row.field(8usize + offset)?.into_u8()?,
            r#previous_quest0: row.field(9usize + offset)?.into_u32()?,
            r#unknown10: row.field(10usize + offset)?.into_u8()?,
            r#previous_quest1: row.field(11usize + offset)?.into_u32()?,
            r#previous_quest2: row.field(12usize + offset)?.into_u32()?,
            r#quest_lock_join: row.field(13usize + offset)?.into_u8()?,
            r#quest_lock: read_array(
                offset,
                2usize,
                1usize,
                |offset| { Result::Ok(row.field(14usize + offset)?.into_u32()?) },
            )?,
            r#header: row.field(16usize + offset)?.into_u16()?,
            r#unknown17: row.field(17usize + offset)?.into_u8()?,
            r#unknown18: row.field(18usize + offset)?.into_u8()?,
            r#class_job_unlock: row.field(19usize + offset)?.into_u8()?,
            r#grand_company: row.field(20usize + offset)?.into_u8()?,
            r#grand_company_rank: row.field(21usize + offset)?.into_u8()?,
            r#instance_content_join: row.field(22usize + offset)?.into_u8()?,
            r#instance_content: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(23usize + offset)?.into_u32()?) },
            )?,
            r#festival: row.field(26usize + offset)?.into_u8()?,
            r#festival_begin: row.field(27usize + offset)?.into_u8()?,
            r#festival_end: row.field(28usize + offset)?.into_u8()?,
            r#bell_start: row.field(29usize + offset)?.into_u16()?,
            r#bell_end: row.field(30usize + offset)?.into_u16()?,
            r#beast_tribe: row.field(31usize + offset)?.into_u8()?,
            r#beast_reputation_rank: row.field(32usize + offset)?.into_u8()?,
            r#beast_reputation_value: row.field(33usize + offset)?.into_u16()?,
            r#satisfaction_npc: row.field(34usize + offset)?.into_u8()?,
            r#satisfaction_level: row.field(35usize + offset)?.into_u8()?,
            r#mount_required: row.field(36usize + offset)?.into_i32()?,
            r#is_house_required: row.field(37usize + offset)?.into_bool()?,
            r#delivery_quest: row.field(38usize + offset)?.into_u8()?,
            r#issuer_start: row.field(39usize + offset)?.into_u32()?,
            r#issuer_location: row.field(40usize + offset)?.into_u32()?,
            r#client_behavior: row.field(41usize + offset)?.into_u16()?,
            r#target_end: row.field(42usize + offset)?.into_u32()?,
            r#is_repeatable: row.field(43usize + offset)?.into_bool()?,
            r#repeat_interval_type: row.field(44usize + offset)?.into_u8()?,
            r#quest_repeat_flag: row.field(45usize + offset)?.into_u8()?,
            r#can_cancel: row.field(46usize + offset)?.into_bool()?,
            r#type: row.field(47usize + offset)?.into_u8()?,
            r#quest_class_job_supply: row.field(48usize + offset)?.into_u16()?,
            r#script_instruction: read_array(
                offset,
                50usize,
                1usize,
                |offset| { Result::Ok(row.field(49usize + offset)?.into_string()?) },
            )?,
            r#script_arg: read_array(
                offset,
                50usize,
                1usize,
                |offset| { Result::Ok(row.field(99usize + offset)?.into_u32()?) },
            )?,
            r#actor_spawn_seq: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(149usize + offset)?.into_u8()?) },
            )?,
            r#actor_despawn_seq: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(213usize + offset)?.into_u8()?) },
            )?,
            r#listener: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(277usize + offset)?.into_u32()?) },
            )?,
            r#quest_u_int8_a: read_array(
                offset,
                32usize,
                1usize,
                |offset| { Result::Ok(row.field(341usize + offset)?.into_u8()?) },
            )?,
            r#quest_u_int8_b: read_array(
                offset,
                32usize,
                1usize,
                |offset| { Result::Ok(row.field(373usize + offset)?.into_u8()?) },
            )?,
            r#condition_type: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(405usize + offset)?.into_u8()?) },
            )?,
            r#condition_value: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(469usize + offset)?.into_u32()?) },
            )?,
            r#condition_operator: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(533usize + offset)?.into_u8()?) },
            )?,
            r#behavior: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(597usize + offset)?.into_u16()?) },
            )?,
            r#visible_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(661usize + offset)?.into_bool()?) },
            )?,
            r#condition_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(725usize + offset)?.into_bool()?) },
            )?,
            r#item_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(789usize + offset)?.into_bool()?) },
            )?,
            r#announce_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(853usize + offset)?.into_bool()?) },
            )?,
            r#behavior_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(917usize + offset)?.into_bool()?) },
            )?,
            r#accept_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(981usize + offset)?.into_bool()?) },
            )?,
            r#qualified_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(1045usize + offset)?.into_bool()?) },
            )?,
            r#can_target_bool: read_array(
                offset,
                64usize,
                1usize,
                |offset| { Result::Ok(row.field(1109usize + offset)?.into_bool()?) },
            )?,
            r#to_do_complete_seq: read_array(
                offset,
                24usize,
                1usize,
                |offset| { Result::Ok(row.field(1173usize + offset)?.into_u8()?) },
            )?,
            r#to_do_qty: read_array(
                offset,
                24usize,
                1usize,
                |offset| { Result::Ok(row.field(1197usize + offset)?.into_u8()?) },
            )?,
            r#to_do_main_location: read_array(
                offset,
                24usize,
                1usize,
                |offset| { Result::Ok(row.field(1221usize + offset)?.into_u32()?) },
            )?,
            r#to_do_child_location: read_array(
                offset,
                7usize,
                24usize,
                |offset| {
                    Result::Ok(
                        read_array(
                            offset,
                            24usize,
                            1usize,
                            |offset| {
                                Result::Ok(row.field(1245usize + offset)?.into_u32()?)
                            },
                        )?,
                    )
                },
            )?,
            r#countable_num: read_array(
                offset,
                24usize,
                1usize,
                |offset| { Result::Ok(row.field(1413usize + offset)?.into_u8()?) },
            )?,
            r#level_max: row.field(1437usize + offset)?.into_u8()?,
            r#class_job_required: row.field(1438usize + offset)?.into_u8()?,
            r#quest_reward_other_display: row.field(1439usize + offset)?.into_u8()?,
            r#exp_factor: row.field(1440usize + offset)?.into_u16()?,
            r#gil_reward: row.field(1441usize + offset)?.into_u32()?,
            r#currency_reward: row.field(1442usize + offset)?.into_u32()?,
            r#currency_reward_count: row.field(1443usize + offset)?.into_u32()?,
            r#item_catalyst: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(1444usize + offset)?.into_u8()?) },
            )?,
            r#item_count_catalyst: read_array(
                offset,
                3usize,
                1usize,
                |offset| { Result::Ok(row.field(1447usize + offset)?.into_u8()?) },
            )?,
            r#item_reward_type: row.field(1450usize + offset)?.into_u8()?,
            r#item_reward: read_array(
                offset,
                7usize,
                1usize,
                |offset| { Result::Ok(row.field(1451usize + offset)?.into_u32()?) },
            )?,
            r#item_count_reward: read_array(
                offset,
                7usize,
                1usize,
                |offset| { Result::Ok(row.field(1458usize + offset)?.into_u8()?) },
            )?,
            r#unknown1465: row.field(1465usize + offset)?.into_bool()?,
            r#unknown1466: row.field(1466usize + offset)?.into_bool()?,
            r#unknown1467: row.field(1467usize + offset)?.into_bool()?,
            r#unknown1468: row.field(1468usize + offset)?.into_bool()?,
            r#unknown1469: row.field(1469usize + offset)?.into_bool()?,
            r#unknown1470: row.field(1470usize + offset)?.into_bool()?,
            r#unknown1471: row.field(1471usize + offset)?.into_bool()?,
            r#stain_reward: read_array(
                offset,
                7usize,
                1usize,
                |offset| { Result::Ok(row.field(1472usize + offset)?.into_u8()?) },
            )?,
            r#optional_item_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1479usize + offset)?.into_u32()?) },
            )?,
            r#optional_item_count_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1484usize + offset)?.into_u8()?) },
            )?,
            r#optional_item_is_hq_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1489usize + offset)?.into_bool()?) },
            )?,
            r#optional_item_stain_reward: read_array(
                offset,
                5usize,
                1usize,
                |offset| { Result::Ok(row.field(1494usize + offset)?.into_u8()?) },
            )?,
            r#emote_reward: row.field(1499usize + offset)?.into_u8()?,
            r#action_reward: row.field(1500usize + offset)?.into_u16()?,
            r#general_action_reward: read_array(
                offset,
                2usize,
                1usize,
                |offset| { Result::Ok(row.field(1501usize + offset)?.into_u8()?) },
            )?,
            r#system_reward0: row.field(1503usize + offset)?.into_u16()?,
            r#other_reward: row.field(1504usize + offset)?.into_u8()?,
            r#system_reward1: row.field(1505usize + offset)?.into_u16()?,
            r#gc_type_reward: row.field(1506usize + offset)?.into_u16()?,
            r#instance_content_unlock: row.field(1507usize + offset)?.into_u32()?,
            r#tomestone: row.field(1508usize + offset)?.into_u8()?,
            r#tomestone_reward: row.field(1509usize + offset)?.into_u8()?,
            r#tomestone_count_reward: row.field(1510usize + offset)?.into_u8()?,
            r#reputation_reward: row.field(1511usize + offset)?.into_u8()?,
            r#place_name: row.field(1512usize + offset)?.into_u16()?,
            r#journal_genre: row.field(1513usize + offset)?.into_u8()?,
            r#unknown1514: row.field(1514usize + offset)?.into_u8()?,
            r#icon: row.field(1515usize + offset)?.into_u32()?,
            r#icon_special: row.field(1516usize + offset)?.into_u32()?,
            r#introduction: row.field(1517usize + offset)?.into_bool()?,
            r#hide_offer_icon: row.field(1518usize + offset)?.into_bool()?,
            r#event_icon_type: row.field(1519usize + offset)?.into_u8()?,
            r#unknown1520: row.field(1520usize + offset)?.into_u8()?,
            r#sort_key: row.field(1521usize + offset)?.into_u16()?,
        })
    }
}
