use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use crate::utility::read_array;
use ironworks::excel::Row;
use std::result::Result;
use std::vec::Vec;
impl MetadataAdapter for RideShooting {
    fn name() -> String {
        "RideShooting".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(RideShooting::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct RideShooting {
    pub r#g_fate_ride_shooting: u16,
    pub r#unknown1: i16,
    pub r#unknown2: i16,
    pub r#unknown3: u16,
    pub r#unknown4: u16,
    pub r#start_text: u16,
    pub r#unknown6: u32,
    pub r#unknown7: u32,
    pub r#unknown8: u32,
    pub r#unknown9: u32,
    pub r#unknown10: u32,
    pub r#unknown11: u32,
    pub r#unknown12: u32,
    pub r#unknown13: u32,
    pub r#pop_range: Vec<u32>,
    pub r#e_npc: Vec<u32>,
    pub r#e_npc_scale: Vec<u8>,
    pub r#unknown38: u32,
    pub r#unknown39: u32,
    pub r#unknown40: u32,
    pub r#unknown41: u32,
    pub r#unknown42: u32,
    pub r#unknown43: u32,
    pub r#unknown44: u32,
    pub r#unknown45: u32,
    pub r#unknown46: u8,
    pub r#unknown47: u8,
    pub r#unknown48: u8,
    pub r#unknown49: u8,
    pub r#unknown50: u8,
    pub r#unknown51: u8,
    pub r#unknown52: u8,
    pub r#unknown53: u8,
    pub r#unknown54: u32,
    pub r#unknown55: u32,
    pub r#unknown56: u32,
    pub r#unknown57: u32,
    pub r#unknown58: u32,
    pub r#unknown59: u32,
    pub r#unknown60: u32,
    pub r#unknown61: u32,
    pub r#unknown62: u8,
    pub r#unknown63: u8,
    pub r#unknown64: u8,
    pub r#unknown65: u8,
    pub r#unknown66: u8,
    pub r#unknown67: u8,
    pub r#unknown68: u8,
    pub r#unknown69: u8,
    pub r#unknown70: u32,
    pub r#unknown71: u32,
    pub r#unknown72: u32,
    pub r#unknown73: u32,
    pub r#unknown74: u32,
    pub r#unknown75: u32,
    pub r#unknown76: u32,
    pub r#unknown77: u32,
    pub r#unknown78: u8,
    pub r#unknown79: u8,
    pub r#unknown80: u8,
    pub r#unknown81: u8,
    pub r#unknown82: u8,
    pub r#unknown83: u8,
    pub r#unknown84: u8,
    pub r#unknown85: u8,
    pub r#unknown86: u32,
    pub r#unknown87: u32,
    pub r#unknown88: u32,
    pub r#unknown89: u32,
    pub r#unknown90: u32,
    pub r#unknown91: u32,
    pub r#unknown92: u32,
    pub r#unknown93: u32,
    pub r#unknown94: u8,
    pub r#unknown95: u8,
    pub r#unknown96: u8,
    pub r#unknown97: u8,
    pub r#unknown98: u8,
    pub r#unknown99: u8,
    pub r#unknown100: u8,
    pub r#unknown101: u8,
    pub r#unknown102: u32,
    pub r#unknown103: u32,
    pub r#unknown104: u32,
    pub r#unknown105: u32,
    pub r#unknown106: u32,
    pub r#unknown107: u32,
    pub r#unknown108: u32,
    pub r#unknown109: u32,
    pub r#unknown110: u8,
    pub r#unknown111: u8,
    pub r#unknown112: u8,
    pub r#unknown113: u8,
    pub r#unknown114: u8,
    pub r#unknown115: u8,
    pub r#unknown116: u8,
    pub r#unknown117: u8,
}
impl RideShooting {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#g_fate_ride_shooting: row.field(0usize + offset)?.into_u16()?,
            r#unknown1: row.field(1usize + offset)?.into_i16()?,
            r#unknown2: row.field(2usize + offset)?.into_i16()?,
            r#unknown3: row.field(3usize + offset)?.into_u16()?,
            r#unknown4: row.field(4usize + offset)?.into_u16()?,
            r#start_text: row.field(5usize + offset)?.into_u16()?,
            r#unknown6: row.field(6usize + offset)?.into_u32()?,
            r#unknown7: row.field(7usize + offset)?.into_u32()?,
            r#unknown8: row.field(8usize + offset)?.into_u32()?,
            r#unknown9: row.field(9usize + offset)?.into_u32()?,
            r#unknown10: row.field(10usize + offset)?.into_u32()?,
            r#unknown11: row.field(11usize + offset)?.into_u32()?,
            r#unknown12: row.field(12usize + offset)?.into_u32()?,
            r#unknown13: row.field(13usize + offset)?.into_u32()?,
            r#pop_range: read_array(
                offset,
                8usize,
                1usize,
                |offset| { Result::Ok(row.field(14usize + offset)?.into_u32()?) },
            )?,
            r#e_npc: read_array(
                offset,
                8usize,
                1usize,
                |offset| { Result::Ok(row.field(22usize + offset)?.into_u32()?) },
            )?,
            r#e_npc_scale: read_array(
                offset,
                8usize,
                1usize,
                |offset| { Result::Ok(row.field(30usize + offset)?.into_u8()?) },
            )?,
            r#unknown38: row.field(38usize + offset)?.into_u32()?,
            r#unknown39: row.field(39usize + offset)?.into_u32()?,
            r#unknown40: row.field(40usize + offset)?.into_u32()?,
            r#unknown41: row.field(41usize + offset)?.into_u32()?,
            r#unknown42: row.field(42usize + offset)?.into_u32()?,
            r#unknown43: row.field(43usize + offset)?.into_u32()?,
            r#unknown44: row.field(44usize + offset)?.into_u32()?,
            r#unknown45: row.field(45usize + offset)?.into_u32()?,
            r#unknown46: row.field(46usize + offset)?.into_u8()?,
            r#unknown47: row.field(47usize + offset)?.into_u8()?,
            r#unknown48: row.field(48usize + offset)?.into_u8()?,
            r#unknown49: row.field(49usize + offset)?.into_u8()?,
            r#unknown50: row.field(50usize + offset)?.into_u8()?,
            r#unknown51: row.field(51usize + offset)?.into_u8()?,
            r#unknown52: row.field(52usize + offset)?.into_u8()?,
            r#unknown53: row.field(53usize + offset)?.into_u8()?,
            r#unknown54: row.field(54usize + offset)?.into_u32()?,
            r#unknown55: row.field(55usize + offset)?.into_u32()?,
            r#unknown56: row.field(56usize + offset)?.into_u32()?,
            r#unknown57: row.field(57usize + offset)?.into_u32()?,
            r#unknown58: row.field(58usize + offset)?.into_u32()?,
            r#unknown59: row.field(59usize + offset)?.into_u32()?,
            r#unknown60: row.field(60usize + offset)?.into_u32()?,
            r#unknown61: row.field(61usize + offset)?.into_u32()?,
            r#unknown62: row.field(62usize + offset)?.into_u8()?,
            r#unknown63: row.field(63usize + offset)?.into_u8()?,
            r#unknown64: row.field(64usize + offset)?.into_u8()?,
            r#unknown65: row.field(65usize + offset)?.into_u8()?,
            r#unknown66: row.field(66usize + offset)?.into_u8()?,
            r#unknown67: row.field(67usize + offset)?.into_u8()?,
            r#unknown68: row.field(68usize + offset)?.into_u8()?,
            r#unknown69: row.field(69usize + offset)?.into_u8()?,
            r#unknown70: row.field(70usize + offset)?.into_u32()?,
            r#unknown71: row.field(71usize + offset)?.into_u32()?,
            r#unknown72: row.field(72usize + offset)?.into_u32()?,
            r#unknown73: row.field(73usize + offset)?.into_u32()?,
            r#unknown74: row.field(74usize + offset)?.into_u32()?,
            r#unknown75: row.field(75usize + offset)?.into_u32()?,
            r#unknown76: row.field(76usize + offset)?.into_u32()?,
            r#unknown77: row.field(77usize + offset)?.into_u32()?,
            r#unknown78: row.field(78usize + offset)?.into_u8()?,
            r#unknown79: row.field(79usize + offset)?.into_u8()?,
            r#unknown80: row.field(80usize + offset)?.into_u8()?,
            r#unknown81: row.field(81usize + offset)?.into_u8()?,
            r#unknown82: row.field(82usize + offset)?.into_u8()?,
            r#unknown83: row.field(83usize + offset)?.into_u8()?,
            r#unknown84: row.field(84usize + offset)?.into_u8()?,
            r#unknown85: row.field(85usize + offset)?.into_u8()?,
            r#unknown86: row.field(86usize + offset)?.into_u32()?,
            r#unknown87: row.field(87usize + offset)?.into_u32()?,
            r#unknown88: row.field(88usize + offset)?.into_u32()?,
            r#unknown89: row.field(89usize + offset)?.into_u32()?,
            r#unknown90: row.field(90usize + offset)?.into_u32()?,
            r#unknown91: row.field(91usize + offset)?.into_u32()?,
            r#unknown92: row.field(92usize + offset)?.into_u32()?,
            r#unknown93: row.field(93usize + offset)?.into_u32()?,
            r#unknown94: row.field(94usize + offset)?.into_u8()?,
            r#unknown95: row.field(95usize + offset)?.into_u8()?,
            r#unknown96: row.field(96usize + offset)?.into_u8()?,
            r#unknown97: row.field(97usize + offset)?.into_u8()?,
            r#unknown98: row.field(98usize + offset)?.into_u8()?,
            r#unknown99: row.field(99usize + offset)?.into_u8()?,
            r#unknown100: row.field(100usize + offset)?.into_u8()?,
            r#unknown101: row.field(101usize + offset)?.into_u8()?,
            r#unknown102: row.field(102usize + offset)?.into_u32()?,
            r#unknown103: row.field(103usize + offset)?.into_u32()?,
            r#unknown104: row.field(104usize + offset)?.into_u32()?,
            r#unknown105: row.field(105usize + offset)?.into_u32()?,
            r#unknown106: row.field(106usize + offset)?.into_u32()?,
            r#unknown107: row.field(107usize + offset)?.into_u32()?,
            r#unknown108: row.field(108usize + offset)?.into_u32()?,
            r#unknown109: row.field(109usize + offset)?.into_u32()?,
            r#unknown110: row.field(110usize + offset)?.into_u8()?,
            r#unknown111: row.field(111usize + offset)?.into_u8()?,
            r#unknown112: row.field(112usize + offset)?.into_u8()?,
            r#unknown113: row.field(113usize + offset)?.into_u8()?,
            r#unknown114: row.field(114usize + offset)?.into_u8()?,
            r#unknown115: row.field(115usize + offset)?.into_u8()?,
            r#unknown116: row.field(116usize + offset)?.into_u8()?,
            r#unknown117: row.field(117usize + offset)?.into_u8()?,
        })
    }
}
