use crate::error::PopulateError;
use crate::metadata::MetadataAdapter;
use crate::utility::read_array;
use ironworks::excel::Row;
use std::result::Result;
use std::vec::Vec;
impl MetadataAdapter for WeeklyLotBonus {
    fn name() -> String {
        "WeeklyLotBonus".to_string()
    }
    fn populate(row: &Row) -> Result<Self, PopulateError> {
        let offset = 0;
        Result::Ok(WeeklyLotBonus::populate(row, offset)?)
    }
}
#[derive(Debug)]
pub struct WeeklyLotBonus {
    pub r#weekly_lot_bonus_threshold: Vec<u8>,
    pub r#unknown31: u8,
    pub r#unknown32: u16,
    pub r#unknown33: u16,
    pub r#unknown34: u16,
    pub r#unknown35: u16,
    pub r#unknown36: u16,
    pub r#unknown37: u16,
    pub r#unknown38: u16,
    pub r#unknown39: u16,
    pub r#unknown40: u16,
    pub r#unknown41: u16,
    pub r#unknown42: u16,
    pub r#unknown43: u16,
    pub r#unknown44: u16,
    pub r#unknown45: u16,
    pub r#unknown46: u16,
    pub r#unknown47: u16,
    pub r#unknown48: u16,
    pub r#unknown49: u16,
    pub r#unknown50: u16,
    pub r#unknown51: u16,
    pub r#unknown52: u16,
    pub r#unknown53: u16,
    pub r#unknown54: u16,
    pub r#unknown55: u16,
    pub r#unknown56: u16,
    pub r#unknown57: u16,
    pub r#unknown58: u16,
    pub r#unknown59: u16,
    pub r#unknown60: u16,
    pub r#unknown61: u16,
    pub r#unknown62: u16,
    pub r#unknown63: u16,
    pub r#unknown64: u8,
    pub r#unknown65: u8,
    pub r#unknown66: u8,
    pub r#unknown67: u8,
    pub r#unknown68: u8,
    pub r#unknown69: u8,
    pub r#unknown70: u8,
    pub r#unknown71: u8,
    pub r#unknown72: u8,
    pub r#unknown73: u8,
    pub r#unknown74: u8,
    pub r#unknown75: u8,
    pub r#unknown76: u8,
    pub r#unknown77: u8,
    pub r#unknown78: u8,
    pub r#unknown79: u8,
    pub r#unknown80: u8,
    pub r#unknown81: u8,
    pub r#unknown82: u8,
    pub r#unknown83: u8,
    pub r#unknown84: u8,
    pub r#unknown85: u8,
    pub r#unknown86: u8,
    pub r#unknown87: u8,
    pub r#unknown88: u8,
    pub r#unknown89: u8,
    pub r#unknown90: u8,
    pub r#unknown91: u8,
    pub r#unknown92: u8,
    pub r#unknown93: u8,
    pub r#unknown94: u8,
    pub r#unknown95: u8,
}
impl WeeklyLotBonus {
    pub fn populate(row: &Row, offset: usize) -> Result<Self, PopulateError> {
        Result::Ok(Self {
            r#weekly_lot_bonus_threshold: read_array(
                offset,
                31usize,
                1usize,
                |offset| { Result::Ok(row.field(0usize + offset)?.into_u8()?) },
            )?,
            r#unknown31: row.field(31usize + offset)?.into_u8()?,
            r#unknown32: row.field(32usize + offset)?.into_u16()?,
            r#unknown33: row.field(33usize + offset)?.into_u16()?,
            r#unknown34: row.field(34usize + offset)?.into_u16()?,
            r#unknown35: row.field(35usize + offset)?.into_u16()?,
            r#unknown36: row.field(36usize + offset)?.into_u16()?,
            r#unknown37: row.field(37usize + offset)?.into_u16()?,
            r#unknown38: row.field(38usize + offset)?.into_u16()?,
            r#unknown39: row.field(39usize + offset)?.into_u16()?,
            r#unknown40: row.field(40usize + offset)?.into_u16()?,
            r#unknown41: row.field(41usize + offset)?.into_u16()?,
            r#unknown42: row.field(42usize + offset)?.into_u16()?,
            r#unknown43: row.field(43usize + offset)?.into_u16()?,
            r#unknown44: row.field(44usize + offset)?.into_u16()?,
            r#unknown45: row.field(45usize + offset)?.into_u16()?,
            r#unknown46: row.field(46usize + offset)?.into_u16()?,
            r#unknown47: row.field(47usize + offset)?.into_u16()?,
            r#unknown48: row.field(48usize + offset)?.into_u16()?,
            r#unknown49: row.field(49usize + offset)?.into_u16()?,
            r#unknown50: row.field(50usize + offset)?.into_u16()?,
            r#unknown51: row.field(51usize + offset)?.into_u16()?,
            r#unknown52: row.field(52usize + offset)?.into_u16()?,
            r#unknown53: row.field(53usize + offset)?.into_u16()?,
            r#unknown54: row.field(54usize + offset)?.into_u16()?,
            r#unknown55: row.field(55usize + offset)?.into_u16()?,
            r#unknown56: row.field(56usize + offset)?.into_u16()?,
            r#unknown57: row.field(57usize + offset)?.into_u16()?,
            r#unknown58: row.field(58usize + offset)?.into_u16()?,
            r#unknown59: row.field(59usize + offset)?.into_u16()?,
            r#unknown60: row.field(60usize + offset)?.into_u16()?,
            r#unknown61: row.field(61usize + offset)?.into_u16()?,
            r#unknown62: row.field(62usize + offset)?.into_u16()?,
            r#unknown63: row.field(63usize + offset)?.into_u16()?,
            r#unknown64: row.field(64usize + offset)?.into_u8()?,
            r#unknown65: row.field(65usize + offset)?.into_u8()?,
            r#unknown66: row.field(66usize + offset)?.into_u8()?,
            r#unknown67: row.field(67usize + offset)?.into_u8()?,
            r#unknown68: row.field(68usize + offset)?.into_u8()?,
            r#unknown69: row.field(69usize + offset)?.into_u8()?,
            r#unknown70: row.field(70usize + offset)?.into_u8()?,
            r#unknown71: row.field(71usize + offset)?.into_u8()?,
            r#unknown72: row.field(72usize + offset)?.into_u8()?,
            r#unknown73: row.field(73usize + offset)?.into_u8()?,
            r#unknown74: row.field(74usize + offset)?.into_u8()?,
            r#unknown75: row.field(75usize + offset)?.into_u8()?,
            r#unknown76: row.field(76usize + offset)?.into_u8()?,
            r#unknown77: row.field(77usize + offset)?.into_u8()?,
            r#unknown78: row.field(78usize + offset)?.into_u8()?,
            r#unknown79: row.field(79usize + offset)?.into_u8()?,
            r#unknown80: row.field(80usize + offset)?.into_u8()?,
            r#unknown81: row.field(81usize + offset)?.into_u8()?,
            r#unknown82: row.field(82usize + offset)?.into_u8()?,
            r#unknown83: row.field(83usize + offset)?.into_u8()?,
            r#unknown84: row.field(84usize + offset)?.into_u8()?,
            r#unknown85: row.field(85usize + offset)?.into_u8()?,
            r#unknown86: row.field(86usize + offset)?.into_u8()?,
            r#unknown87: row.field(87usize + offset)?.into_u8()?,
            r#unknown88: row.field(88usize + offset)?.into_u8()?,
            r#unknown89: row.field(89usize + offset)?.into_u8()?,
            r#unknown90: row.field(90usize + offset)?.into_u8()?,
            r#unknown91: row.field(91usize + offset)?.into_u8()?,
            r#unknown92: row.field(92usize + offset)?.into_u8()?,
            r#unknown93: row.field(93usize + offset)?.into_u8()?,
            r#unknown94: row.field(94usize + offset)?.into_u8()?,
            r#unknown95: row.field(95usize + offset)?.into_u8()?,
        })
    }
}
