[package]
name = "ironworks_schema"
version = "0.2.0"
publish = false

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[features]
exdschema = ["derivative", "git2", "serde", "serde_yaml", "regex"]
saint_coinach = ["derivative", "git2", "serde_json"]

[dependencies]
thiserror.workspace = true

derivative = { workspace = true, optional = true }
git2 = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
