[package]
name = "ironworks"
version = "0.4.1"
description = "Modular FFXIV data toolkit written in rust."
readme = "../README.md"
repository = "https://github.com/ackwell/ironworks"

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
# Modules
excel = [
  "dep:enum-as-inner",
  "dep:num_enum",
  "dep:strum",
  "sestring",
  "exd",
  "exh",
  "exl",
]
sestring = ["dep:num_enum", "dep:time"]
sqpack = ["dep:flate2"]
zipatch = ["patch", "sqpack"]

# File types
eqdp = ["dep:modular-bitfield"]
exd = []
exh = ["dep:num_enum"]
exl = []
mdl = ["dep:half", "dep:modular-bitfield", "dep:num_enum"]
mtrl = []
patch = []
pbd = []
sklb = []
tex = ["dep:num_enum"]

[dependencies]
binrw.workspace = true
derivative.workspace = true
either.workspace = true
getset.workspace = true
thiserror.workspace = true

enum-as-inner = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
half = { workspace = true, optional = true }
modular-bitfield = { workspace = true, optional = true }
num_enum = { workspace = true, optional = true }
strum = { workspace = true, features = ["derive"], optional = true }
time = { workspace = true, optional = true }
